-- Migration: Seed Chart of Accounts and default HMRC Categories
BEGIN;

-- Truncate existing data to avoid conflicts on double-runs
TRUNCATE TABLE public.accounts CASCADE;
TRUNCATE TABLE public.hmrc_categories CASCADE;

INSERT INTO public.accounts (
  code, name, class, group_code, nature, type, statement, vat_default, 
  cashflow_category, statutory_line, description, industry_module, is_active
) VALUES
  (11000, 'INTANGIBLE ASSETS', 1, 11, 'Dr', 'Header', 'BS', NULL, 'Investing', 'Intangible Assets', 'Heading only - do not post', 'UNI', TRUE),
  (11010, 'Goodwill - Cost', 1, 11, 'Dr', 'Posting', 'BS', 'OS', 'Investing', 'Intangible Assets - Goodwill', 'Goodwill arising on acquisition', 'UNI', TRUE),
  (11020, 'Patents & Trademarks - Cost', 1, 11, 'Dr', 'Posting', 'BS', 'S20', 'Investing', 'Intangible Assets - Other', 'Registered patents and trademarks', 'UNI', TRUE),
  (11030, 'Licences & Franchises - Cost', 1, 11, 'Dr', 'Posting', 'BS', 'S20', 'Investing', 'Intangible Assets - Other', 'Acquired licences and franchise rights', 'UNI', TRUE),
  (11040, 'Software & Development - Cost', 1, 11, 'Dr', 'Posting', 'BS', 'S20', 'Investing', 'Intangible Assets - Other', 'Capitalised software and development costs', 'UNI', TRUE),
  (11050, 'Other Intangibles - Cost', 1, 11, 'Dr', 'Posting', 'BS', 'S20', 'Investing', 'Intangible Assets - Other', 'Other intangible assets at cost', 'UNI', TRUE),
  (11910, 'Goodwill - Accumulated Amortisation', 1, 11, 'Cr', 'Posting', 'BS', 'OS', 'N/A', 'Intangible Assets - Goodwill', 'Contra-asset: cumulative amortisation', 'UNI', TRUE),
  (11920, 'Patents & Trademarks - Accumulated Amortisation', 1, 11, 'Cr', 'Posting', 'BS', 'OS', 'N/A', 'Intangible Assets - Other', 'Contra-asset: cumulative amortisation', 'UNI', TRUE),
  (11930, 'Licences & Franchises - Accumulated Amortisation', 1, 11, 'Cr', 'Posting', 'BS', 'OS', 'N/A', 'Intangible Assets - Other', 'Contra-asset: cumulative amortisation', 'UNI', TRUE),
  (11940, 'Software & Development - Accumulated Amortisation', 1, 11, 'Cr', 'Posting', 'BS', 'OS', 'N/A', 'Intangible Assets - Other', 'Contra-asset: cumulative amortisation', 'UNI', TRUE),
  (11950, 'Other Intangibles - Accumulated Amortisation', 1, 11, 'Cr', 'Posting', 'BS', 'OS', 'N/A', 'Intangible Assets - Other', 'Contra-asset: cumulative amortisation', 'UNI', TRUE),
  (12000, 'PROPERTY (LAND & BUILDINGS)', 1, 12, 'Dr', 'Header', 'BS', NULL, 'Investing', 'Tangible Assets - Land & Buildings', 'Heading only - do not post', 'UNI', TRUE),
  (12010, 'Freehold Land - Cost', 1, 12, 'Dr', 'Posting', 'BS', 'OS', 'Investing', 'Tangible Assets - Land & Buildings', 'Freehold land (not depreciated)', 'UNI', TRUE),
  (12020, 'Freehold Buildings - Cost', 1, 12, 'Dr', 'Posting', 'BS', 'S20', 'Investing', 'Tangible Assets - Land & Buildings', 'Freehold buildings at cost or valuation', 'UNI', TRUE),
  (12030, 'Long Leasehold Property - Cost', 1, 12, 'Dr', 'Posting', 'BS', 'S20', 'Investing', 'Tangible Assets - Land & Buildings', 'Leases > 50 years remaining', 'UNI', TRUE),
  (12040, 'Short Leasehold Property - Cost', 1, 12, 'Dr', 'Posting', 'BS', 'S20', 'Investing', 'Tangible Assets - Land & Buildings', 'Leases <= 50 years remaining', 'UNI', TRUE),
  (12050, 'Improvements to Property - Cost', 1, 12, 'Dr', 'Posting', 'BS', 'S20', 'Investing', 'Tangible Assets - Land & Buildings', 'Capital improvements to leased or owned property', 'UNI', TRUE),
  (12920, 'Freehold Buildings - Accumulated Depreciation', 1, 12, 'Cr', 'Posting', 'BS', 'OS', 'N/A', 'Tangible Assets - Land & Buildings', 'Contra-asset', 'UNI', TRUE),
  (12930, 'Long Leasehold - Accumulated Depreciation', 1, 12, 'Cr', 'Posting', 'BS', 'OS', 'N/A', 'Tangible Assets - Land & Buildings', 'Contra-asset', 'UNI', TRUE),
  (12940, 'Short Leasehold - Accumulated Depreciation', 1, 12, 'Cr', 'Posting', 'BS', 'OS', 'N/A', 'Tangible Assets - Land & Buildings', 'Contra-asset', 'UNI', TRUE),
  (12950, 'Property Improvements - Accumulated Depreciation', 1, 12, 'Cr', 'Posting', 'BS', 'OS', 'N/A', 'Tangible Assets - Land & Buildings', 'Contra-asset', 'UNI', TRUE),
  (13000, 'PLANT & MACHINERY', 1, 13, 'Dr', 'Header', 'BS', NULL, 'Investing', 'Tangible Assets - Plant & Machinery', 'Heading only - do not post', 'UNI', TRUE),
  (13010, 'Plant & Machinery - Cost', 1, 13, 'Dr', 'Posting', 'BS', 'S20', 'Investing', 'Tangible Assets - Plant & Machinery', 'Production plant and machinery', 'UNI', TRUE),
  (13020, 'Tools & Equipment - Cost', 1, 13, 'Dr', 'Posting', 'BS', 'S20', 'Investing', 'Tangible Assets - Plant & Machinery', 'Larger tools and working equipment (capitalised)', 'UNI', TRUE),
  (13910, 'Plant & Machinery - Accumulated Depreciation', 1, 13, 'Cr', 'Posting', 'BS', 'OS', 'N/A', 'Tangible Assets - Plant & Machinery', 'Contra-asset', 'UNI', TRUE),
  (13920, 'Tools & Equipment - Accumulated Depreciation', 1, 13, 'Cr', 'Posting', 'BS', 'OS', 'N/A', 'Tangible Assets - Plant & Machinery', 'Contra-asset', 'UNI', TRUE),
  (14000, 'MOTOR VEHICLES', 1, 14, 'Dr', 'Header', 'BS', NULL, 'Investing', 'Tangible Assets - Motor Vehicles', 'Heading only - do not post', 'UNI', TRUE),
  (14010, 'Motor Vehicles - Cost', 1, 14, 'Dr', 'Posting', 'BS', 'S20', 'Investing', 'Tangible Assets - Motor Vehicles', 'Company-owned cars, vans, lorries', 'UNI', TRUE),
  (14910, 'Motor Vehicles - Accumulated Depreciation', 1, 14, 'Cr', 'Posting', 'BS', 'OS', 'N/A', 'Tangible Assets - Motor Vehicles', 'Contra-asset', 'UNI', TRUE),
  (15000, 'FIXTURES, FITTINGS & IT', 1, 15, 'Dr', 'Header', 'BS', NULL, 'Investing', 'Tangible Assets - Fixtures & Fittings', 'Heading only - do not post', 'UNI', TRUE),
  (15010, 'Fixtures & Fittings - Cost', 1, 15, 'Dr', 'Posting', 'BS', 'S20', 'Investing', 'Tangible Assets - Fixtures & Fittings', 'Office furniture, shelving, fittings', 'UNI', TRUE),
  (15020, 'Office Equipment - Cost', 1, 15, 'Dr', 'Posting', 'BS', 'S20', 'Investing', 'Tangible Assets - Fixtures & Fittings', 'Photocopiers, printers, telephones', 'UNI', TRUE),
  (15030, 'Computer Equipment - Cost', 1, 15, 'Dr', 'Posting', 'BS', 'S20', 'Investing', 'Tangible Assets - Fixtures & Fittings', 'PCs, laptops, servers, monitors', 'UNI', TRUE),
  (15040, 'Computer Software (Capitalised) - Cost', 1, 15, 'Dr', 'Posting', 'BS', 'S20', 'Investing', 'Tangible Assets - Fixtures & Fittings', 'Perpetual licences capitalised over 12 months', 'UNI', TRUE),
  (15910, 'Fixtures & Fittings - Accumulated Depreciation', 1, 15, 'Cr', 'Posting', 'BS', 'OS', 'N/A', 'Tangible Assets - Fixtures & Fittings', 'Contra-asset', 'UNI', TRUE),
  (15920, 'Office Equipment - Accumulated Depreciation', 1, 15, 'Cr', 'Posting', 'BS', 'OS', 'N/A', 'Tangible Assets - Fixtures & Fittings', 'Contra-asset', 'UNI', TRUE),
  (15930, 'Computer Equipment - Accumulated Depreciation', 1, 15, 'Cr', 'Posting', 'BS', 'OS', 'N/A', 'Tangible Assets - Fixtures & Fittings', 'Contra-asset', 'UNI', TRUE),
  (15940, 'Computer Software - Accumulated Amortisation', 1, 15, 'Cr', 'Posting', 'BS', 'OS', 'N/A', 'Tangible Assets - Fixtures & Fittings', 'Contra-asset', 'UNI', TRUE),
  (16000, 'INVESTMENTS (NON-CURRENT)', 1, 16, 'Dr', 'Header', 'BS', NULL, 'Investing', 'Investments', 'Heading only - do not post', 'UNI', TRUE),
  (16010, 'Investments in Subsidiaries', 1, 16, 'Dr', 'Posting', 'BS', 'OS', 'Investing', 'Investments', 'Shares in subsidiary undertakings', 'UNI', TRUE),
  (16020, 'Investments in Associates', 1, 16, 'Dr', 'Posting', 'BS', 'OS', 'Investing', 'Investments', 'Shares in associate undertakings', 'UNI', TRUE),
  (16030, 'Investments in Joint Ventures', 1, 16, 'Dr', 'Posting', 'BS', 'OS', 'Investing', 'Investments', 'Interests in joint ventures', 'UNI', TRUE),
  (16040, 'Other Listed Investments', 1, 16, 'Dr', 'Posting', 'BS', 'OS', 'Investing', 'Investments', 'Quoted investments held long-term', 'UNI', TRUE),
  (16050, 'Other Unlisted Investments', 1, 16, 'Dr', 'Posting', 'BS', 'OS', 'Investing', 'Investments', 'Unquoted investments held long-term', 'UNI', TRUE),
  (16060, 'Loans Receivable (> 1 year)', 1, 16, 'Dr', 'Posting', 'BS', 'OS', 'Investing', 'Investments', 'Loans made to third parties > 12 months', 'UNI', TRUE),
  (21000, 'STOCK / INVENTORY', 2, 21, 'Dr', 'Header', 'BS', NULL, 'Operating', 'Stocks', 'Heading only - do not post', 'UNI', TRUE),
  (21010, 'Stock - Raw Materials', 2, 21, 'Dr', 'Posting', 'BS', 'OS', 'Operating', 'Stocks', 'Raw materials held for production', 'UNI', TRUE),
  (21020, 'Stock - Work in Progress (WIP)', 2, 21, 'Dr', 'Posting', 'BS', 'OS', 'Operating', 'Stocks', 'Partly finished goods', 'UNI', TRUE),
  (21030, 'Stock - Finished Goods', 2, 21, 'Dr', 'Posting', 'BS', 'OS', 'Operating', 'Stocks', 'Goods completed and ready for sale', 'UNI', TRUE),
  (21040, 'Stock - Goods for Resale', 2, 21, 'Dr', 'Posting', 'BS', 'OS', 'Operating', 'Stocks', 'Bought-in goods for resale unchanged', 'UNI', TRUE),
  (21050, 'Stock - Consumables', 2, 21, 'Dr', 'Posting', 'BS', 'OS', 'Operating', 'Stocks', 'Production consumables held', 'UNI', TRUE),
  (21060, 'Stock in Transit', 2, 21, 'Dr', 'Posting', 'BS', 'OS', 'Operating', 'Stocks', 'Goods purchased, in transit, not yet received', 'UNI', TRUE),
  (22000, 'TRADE & OTHER DEBTORS', 2, 22, 'Dr', 'Header', 'BS', NULL, 'Operating', 'Debtors', 'Heading only - do not post', 'UNI', TRUE),
  (22010, 'Trade Debtors (Sales Ledger Control)', 2, 22, 'Dr', 'Posting', 'BS', 'OS', 'Operating', 'Debtors - Trade', 'Control account for customer invoices', 'UNI', TRUE),
  (22020, 'Trade Debtors - Foreign Currency', 2, 22, 'Dr', 'Posting', 'BS', 'OS', 'Operating', 'Debtors - Trade', 'Foreign currency customer balances', 'UNI', TRUE),
  (22030, 'Other Debtors', 2, 22, 'Dr', 'Posting', 'BS', 'OS', 'Operating', 'Debtors - Other', 'Non-trade amounts receivable', 'UNI', TRUE),
  (22040, 'Loans to Employees', 2, 22, 'Dr', 'Posting', 'BS', 'OS', 'Operating', 'Debtors - Other', 'Staff loans and advances', 'UNI', TRUE),
  (22050, 'Amounts Owed by Group Undertakings', 2, 22, 'Dr', 'Posting', 'BS', 'OS', 'Operating', 'Debtors - Group', 'Intercompany receivables', 'UNI', TRUE),
  (22060, 'Amounts Owed by Associates', 2, 22, 'Dr', 'Posting', 'BS', 'OS', 'Operating', 'Debtors - Group', 'Receivables from associates', 'UNI', TRUE),
  (22070, 'Director''s Loan Account (Debit)', 2, 22, 'Dr', 'Posting', 'BS', 'OS', 'Financing', 'Debtors - Other', 'Use when director owes the company', 'UNI', TRUE),
  (23000, 'PREPAYMENTS & ACCRUED INCOME', 2, 23, 'Dr', 'Header', 'BS', NULL, 'Operating', 'Prepayments', 'Heading only - do not post', 'UNI', TRUE),
  (23010, 'Prepayments', 2, 23, 'Dr', 'Posting', 'BS', 'OS', 'Operating', 'Prepayments', 'Expenses paid in advance', 'UNI', TRUE),
  (23020, 'Accrued Income', 2, 23, 'Dr', 'Posting', 'BS', 'OS', 'Operating', 'Prepayments', 'Income earned, not yet invoiced', 'UNI', TRUE),
  (23030, 'Deposits Paid', 2, 23, 'Dr', 'Posting', 'BS', 'OS', 'Operating', 'Prepayments', 'Deposits to suppliers / landlords', 'UNI', TRUE),
  (23040, 'Insurance Prepaid', 2, 23, 'Dr', 'Posting', 'BS', 'OS', 'Operating', 'Prepayments', 'Unexpired insurance premiums', 'UNI', TRUE),
  (23050, 'Rent Prepaid', 2, 23, 'Dr', 'Posting', 'BS', 'OS', 'Operating', 'Prepayments', 'Rent paid in advance', 'UNI', TRUE),
  (24000, 'CASH AT BANK', 2, 24, 'Dr', 'Header', 'BS', NULL, 'Operating', 'Cash at Bank & in Hand', 'Heading only - do not post', 'UNI', TRUE),
  (24010, 'Current Account - Main (GBP)', 2, 24, 'Dr', 'Posting', 'BS', 'OS', 'Operating', 'Cash at Bank & in Hand', 'Primary GBP current account', 'UNI', TRUE),
  (24020, 'Current Account - Secondary (GBP)', 2, 24, 'Dr', 'Posting', 'BS', 'OS', 'Operating', 'Cash at Bank & in Hand', 'Second GBP current account', 'UNI', TRUE),
  (24030, 'Deposit / Savings Account', 2, 24, 'Dr', 'Posting', 'BS', 'OS', 'Operating', 'Cash at Bank & in Hand', 'Interest-bearing deposit', 'UNI', TRUE),
  (24040, 'Foreign Currency Account - USD', 2, 24, 'Dr', 'Posting', 'BS', 'OS', 'Operating', 'Cash at Bank & in Hand', 'USD-denominated bank account', 'UNI', TRUE),
  (24050, 'Foreign Currency Account - EUR', 2, 24, 'Dr', 'Posting', 'BS', 'OS', 'Operating', 'Cash at Bank & in Hand', 'EUR-denominated bank account', 'UNI', TRUE),
  (24060, 'Merchant Account / Payment Gateway', 2, 24, 'Dr', 'Posting', 'BS', 'OS', 'Operating', 'Cash at Bank & in Hand', 'Stripe / Worldpay / PayPal balances', 'UNI', TRUE),
  (24070, 'Bank Account - In Transit', 2, 24, 'Dr', 'Posting', 'BS', 'OS', 'Operating', 'Cash at Bank & in Hand', 'Cash in transit between accounts', 'UNI', TRUE),
  (25000, 'CASH IN HAND', 2, 25, 'Dr', 'Header', 'BS', NULL, 'Operating', 'Cash at Bank & in Hand', 'Heading only - do not post', 'UNI', TRUE),
  (25010, 'Petty Cash', 2, 25, 'Dr', 'Posting', 'BS', 'OS', 'Operating', 'Cash at Bank & in Hand', 'Office petty cash float', 'UNI', TRUE),
  (25020, 'Cash Float (Till)', 2, 25, 'Dr', 'Posting', 'BS', 'OS', 'Operating', 'Cash at Bank & in Hand', 'Till / register cash', 'UNI', TRUE),
  (26000, 'VAT RECOVERABLE & CIS SUFFERED', 2, 26, 'Dr', 'Header', 'BS', NULL, 'Operating', 'Debtors - Other', 'Heading only - do not post', 'UNI', TRUE),
  (26010, 'VAT Input - Standard Rate (20%)', 2, 26, 'Dr', 'Posting', 'BS', 'OS', 'Operating', 'Debtors - Other', 'VAT recoverable on purchases at 20%', 'UNI', TRUE),
  (26020, 'VAT Input - Reduced Rate (5%)', 2, 26, 'Dr', 'Posting', 'BS', 'OS', 'Operating', 'Debtors - Other', 'VAT recoverable on purchases at 5%', 'UNI', TRUE),
  (26030, 'VAT Input - Reverse Charge', 2, 26, 'Dr', 'Posting', 'BS', 'OS', 'Operating', 'Debtors - Other', 'Reverse charge input (mirrored in 34040)', 'UNI', TRUE),
  (26040, 'VAT Refund Receivable from HMRC', 2, 26, 'Dr', 'Posting', 'BS', 'OS', 'Operating', 'Debtors - Other', 'Net VAT recoverable when input > output', 'UNI', TRUE),
  (26050, 'CIS Tax Suffered (Recoverable)', 2, 26, 'Dr', 'Posting', 'BS', 'OS', 'Operating', 'Debtors - Other', 'CIS deducted by contractors from us', 'UNI', TRUE),
  (29000, 'PROVISIONS AGAINST ASSETS', 2, 29, 'Cr', 'Header', 'BS', NULL, 'Operating', 'Debtors - Trade', 'Heading only - do not post', 'UNI', TRUE),
  (29010, 'Provision for Doubtful Debts', 2, 29, 'Cr', 'Posting', 'BS', 'OS', 'Operating', 'Debtors - Trade', 'Contra-asset: doubtful debt provision', 'UNI', TRUE),
  (31000, 'TRADE CREDITORS', 3, 31, 'Cr', 'Header', 'BS', NULL, 'Operating', 'Creditors < 1yr - Trade', 'Heading only - do not post', 'UNI', TRUE),
  (31010, 'Trade Creditors (Purchase Ledger Control)', 3, 31, 'Cr', 'Posting', 'BS', 'OS', 'Operating', 'Creditors < 1yr - Trade', 'Control account for supplier invoices', 'UNI', TRUE),
  (31020, 'Trade Creditors - Foreign Currency', 3, 31, 'Cr', 'Posting', 'BS', 'OS', 'Operating', 'Creditors < 1yr - Trade', 'Foreign currency supplier balances', 'UNI', TRUE),
  (32000, 'OTHER CREDITORS', 3, 32, 'Cr', 'Header', 'BS', NULL, 'Operating', 'Creditors < 1yr - Other', 'Heading only - do not post', 'UNI', TRUE),
  (32010, 'Other Creditors', 3, 32, 'Cr', 'Posting', 'BS', 'OS', 'Operating', 'Creditors < 1yr - Other', 'Non-trade amounts payable', 'UNI', TRUE),
  (32020, 'Amounts Owed to Group Undertakings', 3, 32, 'Cr', 'Posting', 'BS', 'OS', 'Operating', 'Creditors < 1yr - Group', 'Intercompany payables', 'UNI', TRUE),
  (32030, 'Amounts Owed to Associates', 3, 32, 'Cr', 'Posting', 'BS', 'OS', 'Operating', 'Creditors < 1yr - Group', 'Payables to associates', 'UNI', TRUE),
  (32040, 'Customer Deposits / Payments on Account', 3, 32, 'Cr', 'Posting', 'BS', 'OS', 'Operating', 'Creditors < 1yr - Other', 'Advance receipts from customers', 'UNI', TRUE),
  (32050, 'Bills of Exchange Payable', 3, 32, 'Cr', 'Posting', 'BS', 'OS', 'Operating', 'Creditors < 1yr - Other', 'Acceptances and bills payable', 'UNI', TRUE),
  (33000, 'ACCRUALS & DEFERRED INCOME', 3, 33, 'Cr', 'Header', 'BS', NULL, 'Operating', 'Accruals & Deferred Income', 'Heading only - do not post', 'UNI', TRUE),
  (33010, 'Accrued Expenses', 3, 33, 'Cr', 'Posting', 'BS', 'OS', 'Operating', 'Accruals & Deferred Income', 'Expenses incurred, not yet invoiced', 'UNI', TRUE),
  (33020, 'Deferred Income', 3, 33, 'Cr', 'Posting', 'BS', 'OS', 'Operating', 'Accruals & Deferred Income', 'Income received in advance', 'UNI', TRUE),
  (33030, 'Deferred Grants', 3, 33, 'Cr', 'Posting', 'BS', 'OS', 'Operating', 'Accruals & Deferred Income', 'Capital grants deferred over asset life', 'UNI', TRUE),
  (34000, 'TAX & STATUTORY LIABILITIES', 3, 34, 'Cr', 'Header', 'BS', NULL, 'Operating', 'Creditors < 1yr - Taxation', 'Heading only - do not post', 'UNI', TRUE),
  (34010, 'VAT Output - Standard Rate (20%)', 3, 34, 'Cr', 'Posting', 'BS', 'OS', 'Operating', 'Creditors < 1yr - Taxation', 'VAT charged on sales at 20%', 'UNI', TRUE),
  (34020, 'VAT Output - Reduced Rate (5%)', 3, 34, 'Cr', 'Posting', 'BS', 'OS', 'Operating', 'Creditors < 1yr - Taxation', 'VAT charged on sales at 5%', 'UNI', TRUE),
  (34030, 'VAT Output - Zero Rate', 3, 34, 'Cr', 'Posting', 'BS', 'OS', 'Operating', 'Creditors < 1yr - Taxation', 'Memo: zero-rated sales VAT', 'UNI', TRUE),
  (34040, 'VAT Output - Reverse Charge', 3, 34, 'Cr', 'Posting', 'BS', 'OS', 'Operating', 'Creditors < 1yr - Taxation', 'Reverse charge output (mirrored in 26030)', 'UNI', TRUE),
  (34050, 'VAT Payable to HMRC (Control)', 3, 34, 'Cr', 'Posting', 'BS', 'OS', 'Operating', 'Creditors < 1yr - Taxation', 'Net VAT due to HMRC each quarter', 'UNI', TRUE),
  (34110, 'PAYE Payable', 3, 34, 'Cr', 'Posting', 'BS', 'OS', 'Operating', 'Creditors < 1yr - Taxation', 'Income tax withheld from employees', 'UNI', TRUE),
  (34120, 'Employee NI Payable', 3, 34, 'Cr', 'Posting', 'BS', 'OS', 'Operating', 'Creditors < 1yr - Taxation', 'Employee national insurance withheld', 'UNI', TRUE),
  (34130, 'Employer NI Payable', 3, 34, 'Cr', 'Posting', 'BS', 'OS', 'Operating', 'Creditors < 1yr - Taxation', 'Employer national insurance owed', 'UNI', TRUE),
  (34140, 'Student Loan Deductions Payable', 3, 34, 'Cr', 'Posting', 'BS', 'OS', 'Operating', 'Creditors < 1yr - Taxation', 'Student loan deductions to HMRC', 'UNI', TRUE),
  (34150, 'Pension Contributions Payable', 3, 34, 'Cr', 'Posting', 'BS', 'OS', 'Operating', 'Creditors < 1yr - Other', 'Workplace pension owed to provider', 'UNI', TRUE),
  (34160, 'Attachment of Earnings Payable', 3, 34, 'Cr', 'Posting', 'BS', 'OS', 'Operating', 'Creditors < 1yr - Other', 'Court-ordered deductions payable', 'UNI', TRUE),
  (34220, 'CIS Deducted - Owed to HMRC', 3, 34, 'Cr', 'Posting', 'BS', 'OS', 'Operating', 'Creditors < 1yr - Taxation', 'CIS we deducted from our subcontractors', 'UNI', TRUE),
  (34310, 'Corporation Tax Payable (Current)', 3, 34, 'Cr', 'Posting', 'BS', 'OS', 'Operating', 'Creditors < 1yr - Taxation', 'Current year CT liability', 'UNI', TRUE),
  (34320, 'Corporation Tax Payable (Prior Year)', 3, 34, 'Cr', 'Posting', 'BS', 'OS', 'Operating', 'Creditors < 1yr - Taxation', 'Prior year CT not yet paid', 'UNI', TRUE),
  (35000, 'SHORT-TERM LOANS & OVERDRAFTS', 3, 35, 'Cr', 'Header', 'BS', NULL, 'Financing', 'Creditors < 1yr - Bank', 'Heading only - do not post', 'UNI', TRUE),
  (35010, 'Bank Overdraft', 3, 35, 'Cr', 'Posting', 'BS', 'OS', 'Financing', 'Creditors < 1yr - Bank', 'Bank current account overdrawn', 'UNI', TRUE),
  (35020, 'Bank Loan - Current Portion', 3, 35, 'Cr', 'Posting', 'BS', 'OS', 'Financing', 'Creditors < 1yr - Bank', 'Loan instalments due within 12 months', 'UNI', TRUE),
  (35030, 'Other Short-term Loans', 3, 35, 'Cr', 'Posting', 'BS', 'OS', 'Financing', 'Creditors < 1yr - Other', 'Non-bank short-term borrowings', 'UNI', TRUE),
  (35040, 'Hire Purchase - Current Portion', 3, 35, 'Cr', 'Posting', 'BS', 'OS', 'Financing', 'Creditors < 1yr - Other', 'HP instalments due < 12 months', 'UNI', TRUE),
  (35050, 'Finance Lease - Current Portion', 3, 35, 'Cr', 'Posting', 'BS', 'OS', 'Financing', 'Creditors < 1yr - Other', 'Finance lease due < 12 months', 'UNI', TRUE),
  (36000, 'DIRECTORS'' LOAN ACCOUNTS', 3, 36, 'Cr', 'Header', 'BS', NULL, 'Financing', 'Creditors < 1yr - Other', 'Heading only - do not post', 'UNI', TRUE),
  (36010, 'Director''s Loan Account (Credit)', 3, 36, 'Cr', 'Posting', 'BS', 'OS', 'Financing', 'Creditors < 1yr - Other', 'Use when company owes the director', 'UNI', TRUE),
  (37000, 'PAYROLL CONTROL', 3, 37, 'Cr', 'Header', 'BS', NULL, 'Operating', 'Creditors < 1yr - Other', 'Heading only - do not post', 'UNI', TRUE),
  (37010, 'Net Wages Payable', 3, 37, 'Cr', 'Posting', 'BS', 'OS', 'Operating', 'Creditors < 1yr - Other', 'Net pay owed to employees', 'UNI', TRUE),
  (37020, 'Wages Control Account', 3, 37, 'Cr', 'Posting', 'BS', 'OS', 'Operating', 'Creditors < 1yr - Other', 'Payroll suspense / control', 'UNI', TRUE),
  (38000, 'DIVIDENDS PAYABLE', 3, 38, 'Cr', 'Header', 'BS', NULL, 'Financing', 'Creditors < 1yr - Other', 'Heading only - do not post', 'UNI', TRUE),
  (38010, 'Dividends Proposed', 3, 38, 'Cr', 'Posting', 'BS', 'OS', 'Financing', 'Creditors < 1yr - Other', 'Proposed dividends not yet declared', 'UNI', TRUE),
  (38020, 'Dividends Declared, Unpaid', 3, 38, 'Cr', 'Posting', 'BS', 'OS', 'Financing', 'Creditors < 1yr - Other', 'Declared dividends pending payment', 'UNI', TRUE),
  (41000, 'LONG-TERM BANK & OTHER LOANS', 4, 41, 'Cr', 'Header', 'BS', NULL, 'Financing', 'Creditors > 1yr - Bank', 'Heading only - do not post', 'UNI', TRUE),
  (41010, 'Bank Loan - Long-term (Secured)', 4, 41, 'Cr', 'Posting', 'BS', 'OS', 'Financing', 'Creditors > 1yr - Bank', 'Secured bank loans due > 12 months', 'UNI', TRUE),
  (41020, 'Bank Loan - Long-term (Unsecured)', 4, 41, 'Cr', 'Posting', 'BS', 'OS', 'Financing', 'Creditors > 1yr - Bank', 'Unsecured bank loans due > 12 months', 'UNI', TRUE),
  (41030, 'Mortgage Loan', 4, 41, 'Cr', 'Posting', 'BS', 'OS', 'Financing', 'Creditors > 1yr - Bank', 'Property mortgage', 'UNI', TRUE),
  (41040, 'Loan from Director (> 1 year)', 4, 41, 'Cr', 'Posting', 'BS', 'OS', 'Financing', 'Creditors > 1yr - Other', 'Director loan > 12 months', 'UNI', TRUE),
  (41050, 'Loan from Connected Party (> 1 year)', 4, 41, 'Cr', 'Posting', 'BS', 'OS', 'Financing', 'Creditors > 1yr - Other', 'Related party loan > 12 months', 'UNI', TRUE),
  (41060, 'Other Long-term Loans', 4, 41, 'Cr', 'Posting', 'BS', 'OS', 'Financing', 'Creditors > 1yr - Other', 'Other long-term borrowings', 'UNI', TRUE),
  (42000, 'HIRE PURCHASE & FINANCE LEASES', 4, 42, 'Cr', 'Header', 'BS', NULL, 'Financing', 'Creditors > 1yr - Other', 'Heading only - do not post', 'UNI', TRUE),
  (42010, 'Hire Purchase Obligations (> 1 year)', 4, 42, 'Cr', 'Posting', 'BS', 'OS', 'Financing', 'Creditors > 1yr - Other', 'HP balance due > 12 months', 'UNI', TRUE),
  (42020, 'Finance Lease Obligations (> 1 year)', 4, 42, 'Cr', 'Posting', 'BS', 'OS', 'Financing', 'Creditors > 1yr - Other', 'Finance lease balance > 12 months', 'UNI', TRUE),
  (43000, 'DEBENTURES & CONVERTIBLES', 4, 43, 'Cr', 'Header', 'BS', NULL, 'Financing', 'Creditors > 1yr - Other', 'Heading only - do not post', 'UNI', TRUE),
  (43010, 'Debenture Loans', 4, 43, 'Cr', 'Posting', 'BS', 'OS', 'Financing', 'Creditors > 1yr - Other', 'Issued debenture stock', 'UNI', TRUE),
  (43020, 'Convertible Loan Notes', 4, 43, 'Cr', 'Posting', 'BS', 'OS', 'Financing', 'Creditors > 1yr - Other', 'Loan notes convertible to equity', 'UNI', TRUE),
  (44000, 'PROVISIONS FOR LIABILITIES', 4, 44, 'Cr', 'Header', 'BS', NULL, 'Operating', 'Provisions for Liabilities', 'Heading only - do not post', 'UNI', TRUE),
  (44010, 'Provision for Warranty Claims', 4, 44, 'Cr', 'Posting', 'BS', 'OS', 'Operating', 'Provisions for Liabilities', 'Estimated future warranty costs', 'UNI', TRUE),
  (44020, 'Provision for Legal Claims', 4, 44, 'Cr', 'Posting', 'BS', 'OS', 'Operating', 'Provisions for Liabilities', 'Estimated legal settlements', 'UNI', TRUE),
  (44030, 'Provision for Restructuring', 4, 44, 'Cr', 'Posting', 'BS', 'OS', 'Operating', 'Provisions for Liabilities', 'Restructuring provisions', 'UNI', TRUE),
  (44040, 'Provision for Onerous Contracts', 4, 44, 'Cr', 'Posting', 'BS', 'OS', 'Operating', 'Provisions for Liabilities', 'Loss-making contract provisions', 'UNI', TRUE),
  (44050, 'Other Provisions', 4, 44, 'Cr', 'Posting', 'BS', 'OS', 'Operating', 'Provisions for Liabilities', 'Other provisions for liabilities', 'UNI', TRUE),
  (45000, 'DEFERRED TAX', 4, 45, 'Cr', 'Header', 'BS', NULL, 'Operating', 'Provisions for Liabilities - Deferred Tax', 'Heading only - do not post', 'UNI', TRUE),
  (45010, 'Deferred Tax Liability', 4, 45, 'Cr', 'Posting', 'BS', 'OS', 'Operating', 'Provisions for Liabilities - Deferred Tax', 'Deferred tax balance', 'UNI', TRUE),
  (51000, 'SHARE CAPITAL', 5, 51, 'Cr', 'Header', 'BS', NULL, 'Financing', 'Called Up Share Capital', 'Heading only - do not post', 'UNI', TRUE),
  (51010, 'Ordinary Share Capital', 5, 51, 'Cr', 'Posting', 'BS', 'OS', 'Financing', 'Called Up Share Capital', 'Issued ordinary shares (nominal value)', 'UNI', TRUE),
  (51020, 'Preference Share Capital', 5, 51, 'Cr', 'Posting', 'BS', 'OS', 'Financing', 'Called Up Share Capital', 'Issued preference shares (nominal value)', 'UNI', TRUE),
  (51030, 'Deferred Shares', 5, 51, 'Cr', 'Posting', 'BS', 'OS', 'Financing', 'Called Up Share Capital', 'Deferred share class', 'UNI', TRUE),
  (51040, 'Share Capital - Called Up Not Paid', 5, 51, 'Dr', 'Posting', 'BS', 'OS', 'Financing', 'Called Up Share Capital Not Paid', 'Called up share capital unpaid by shareholders', 'UNI', TRUE),
  (52000, 'SHARE PREMIUM', 5, 52, 'Cr', 'Header', 'BS', NULL, 'Financing', 'Share Premium', 'Heading only - do not post', 'UNI', TRUE),
  (52010, 'Share Premium Account', 5, 52, 'Cr', 'Posting', 'BS', 'OS', 'Financing', 'Share Premium', 'Amount paid above nominal value', 'UNI', TRUE),
  (53000, 'RETAINED EARNINGS', 5, 53, 'Cr', 'Header', 'BS', NULL, 'N/A', 'Profit & Loss Account', 'Heading only - do not post', 'UNI', TRUE),
  (53010, 'P&L Account - Brought Forward', 5, 53, 'Cr', 'Posting', 'BS', 'OS', 'N/A', 'Profit & Loss Account', 'Accumulated profits at start of year', 'UNI', TRUE),
  (53020, 'P&L Account - Current Year', 5, 53, 'Cr', 'Posting', 'BS', 'OS', 'N/A', 'Profit & Loss Account', 'Auto-populated at year end', 'UNI', TRUE),
  (53030, 'Prior Year Adjustments', 5, 53, 'Cr', 'Posting', 'BS', 'OS', 'N/A', 'Profit & Loss Account', 'Corrections to prior year earnings', 'UNI', TRUE),
  (54000, 'REVALUATION RESERVE', 5, 54, 'Cr', 'Header', 'BS', NULL, 'N/A', 'Revaluation Reserve', 'Heading only - do not post', 'UNI', TRUE),
  (54010, 'Revaluation Reserve', 5, 54, 'Cr', 'Posting', 'BS', 'OS', 'N/A', 'Revaluation Reserve', 'Gains on revaluation of fixed assets', 'UNI', TRUE),
  (55000, 'OTHER RESERVES', 5, 55, 'Cr', 'Header', 'BS', NULL, 'N/A', 'Other Reserves', 'Heading only - do not post', 'UNI', TRUE),
  (55010, 'Capital Redemption Reserve', 5, 55, 'Cr', 'Posting', 'BS', 'OS', 'N/A', 'Other Reserves', 'Created on share buybacks', 'UNI', TRUE),
  (55020, 'Share Options Reserve', 5, 55, 'Cr', 'Posting', 'BS', 'OS', 'N/A', 'Other Reserves', 'Equity-settled share-based payments', 'UNI', TRUE),
  (55030, 'Fair Value Reserve', 5, 55, 'Cr', 'Posting', 'BS', 'OS', 'N/A', 'Other Reserves', 'Fair value movements on investments', 'UNI', TRUE),
  (55040, 'General Reserve', 5, 55, 'Cr', 'Posting', 'BS', 'OS', 'N/A', 'Other Reserves', 'Voluntary transfers from P&L', 'UNI', TRUE),
  (55050, 'Foreign Exchange Reserve', 5, 55, 'Cr', 'Posting', 'BS', 'OS', 'N/A', 'Other Reserves', 'Translation of foreign operations', 'UNI', TRUE),
  (56000, 'DIVIDENDS PAID', 5, 56, 'Dr', 'Header', 'BS', NULL, 'Financing', 'Profit & Loss Account', 'Heading only - do not post', 'UNI', TRUE),
  (56010, 'Equity Dividends Paid', 5, 56, 'Dr', 'Posting', 'BS', 'OS', 'Financing', 'Profit & Loss Account', 'Dividends paid to ordinary shareholders', 'UNI', TRUE),
  (56020, 'Preference Dividends Paid', 5, 56, 'Dr', 'Posting', 'BS', 'OS', 'Financing', 'Profit & Loss Account', 'Dividends paid to preference shareholders', 'UNI', TRUE),
  (61000, 'SALES OF GOODS', 6, 61, 'Cr', 'Header', 'PL', NULL, 'Operating', 'Turnover', 'Heading only - do not post', 'UNI', TRUE),
  (61010, 'Sales - Standard Rated (UK)', 6, 61, 'Cr', 'Posting', 'PL', 'S20', 'Operating', 'Turnover', 'Domestic sales at 20% VAT', 'UNI', TRUE),
  (61020, 'Sales - Reduced Rated (UK)', 6, 61, 'Cr', 'Posting', 'PL', 'R5', 'Operating', 'Turnover', 'Domestic sales at 5% VAT', 'UNI', TRUE),
  (61030, 'Sales - Zero Rated (UK)', 6, 61, 'Cr', 'Posting', 'PL', 'Z', 'Operating', 'Turnover', 'Zero-rated domestic sales', 'UNI', TRUE),
  (61040, 'Sales - Exempt (UK)', 6, 61, 'Cr', 'Posting', 'PL', 'E', 'Operating', 'Turnover', 'VAT-exempt domestic sales', 'UNI', TRUE),
  (61050, 'Sales - Wholesale', 6, 61, 'Cr', 'Posting', 'PL', 'S20', 'Operating', 'Turnover', 'Trade / wholesale sales channel', 'UNI', TRUE),
  (61060, 'Sales - Retail', 6, 61, 'Cr', 'Posting', 'PL', 'S20', 'Operating', 'Turnover', 'Retail / consumer sales channel', 'UNI', TRUE),
  (61070, 'Sales - Online / E-commerce', 6, 61, 'Cr', 'Posting', 'PL', 'S20', 'Operating', 'Turnover', 'Sales via online channels', 'UNI', TRUE),
  (62000, 'SALES OF SERVICES', 6, 62, 'Cr', 'Header', 'PL', NULL, 'Operating', 'Turnover', 'Heading only - do not post', 'UNI', TRUE),
  (62010, 'Service Income - Standard Rated', 6, 62, 'Cr', 'Posting', 'PL', 'S20', 'Operating', 'Turnover', 'Services billed at 20% VAT', 'UNI', TRUE),
  (62020, 'Service Income - Zero Rated', 6, 62, 'Cr', 'Posting', 'PL', 'Z', 'Operating', 'Turnover', 'Zero-rated service income', 'UNI', TRUE),
  (62030, 'Service Income - Exempt', 6, 62, 'Cr', 'Posting', 'PL', 'E', 'Operating', 'Turnover', 'VAT-exempt service income', 'UNI', TRUE),
  (62040, 'Consultancy Fees', 6, 62, 'Cr', 'Posting', 'PL', 'S20', 'Operating', 'Turnover', 'Consultancy income', 'UNI', TRUE),
  (62050, 'Professional Fees Earned', 6, 62, 'Cr', 'Posting', 'PL', 'S20', 'Operating', 'Turnover', 'Professional services income', 'UNI', TRUE),
  (62060, 'Subscription Income', 6, 62, 'Cr', 'Posting', 'PL', 'S20', 'Operating', 'Turnover', 'Recurring subscription revenue', 'UNI', TRUE),
  (62070, 'Commission Earned', 6, 62, 'Cr', 'Posting', 'PL', 'S20', 'Operating', 'Turnover', 'Commission income from third parties', 'UNI', TRUE),
  (63000, 'EXPORT SALES', 6, 63, 'Cr', 'Header', 'PL', NULL, 'Operating', 'Turnover', 'Heading only - do not post', 'UNI', TRUE),
  (63010, 'Export Sales - Goods (Outside UK)', 6, 63, 'Cr', 'Posting', 'PL', 'Z', 'Operating', 'Turnover', 'Goods exported outside UK', 'UNI', TRUE),
  (63020, 'Export Sales - Services (Outside UK)', 6, 63, 'Cr', 'Posting', 'PL', 'OS', 'Operating', 'Turnover', 'Services to overseas customers', 'UNI', TRUE),
  (63030, 'EU Sales - B2B (Reverse Charge)', 6, 63, 'Cr', 'Posting', 'PL', 'RC', 'Operating', 'Turnover', 'B2B EU sales under reverse charge', 'UNI', TRUE),
  (63040, 'EU Sales - B2C', 6, 63, 'Cr', 'Posting', 'PL', 'S20', 'Operating', 'Turnover', 'B2C EU sales (where applicable)', 'UNI', TRUE),
  (64000, 'OTHER TRADING INCOME', 6, 64, 'Cr', 'Header', 'PL', NULL, 'Operating', 'Turnover', 'Heading only - do not post', 'UNI', TRUE),
  (64010, 'Rental Income', 6, 64, 'Cr', 'Posting', 'PL', 'E', 'Operating', 'Turnover', 'Property rental income', 'UNI', TRUE),
  (64020, 'Royalties Received', 6, 64, 'Cr', 'Posting', 'PL', 'S20', 'Operating', 'Turnover', 'Royalty income', 'UNI', TRUE),
  (64030, 'Licence Fees Received', 6, 64, 'Cr', 'Posting', 'PL', 'S20', 'Operating', 'Turnover', 'Licence income', 'UNI', TRUE),
  (64040, 'Other Trading Income', 6, 64, 'Cr', 'Posting', 'PL', 'S20', 'Operating', 'Turnover', 'Miscellaneous trading income', 'UNI', TRUE),
  (65000, 'DISCOUNTS & REBATES RECEIVED', 6, 65, 'Cr', 'Header', 'PL', NULL, 'Operating', 'Turnover', 'Heading only - do not post', 'UNI', TRUE),
  (65010, 'Discounts Received (Settlement)', 6, 65, 'Cr', 'Posting', 'PL', 'OS', 'Operating', 'Turnover', 'Early payment discounts from suppliers', 'UNI', TRUE),
  (65020, 'Volume Rebates Received', 6, 65, 'Cr', 'Posting', 'PL', 'OS', 'Operating', 'Turnover', 'Supplier volume rebates', 'UNI', TRUE),
  (69000, 'SALES RETURNS & DISCOUNTS ALLOWED', 6, 69, 'Dr', 'Header', 'PL', NULL, 'Operating', 'Turnover (contra)', 'Heading only - do not post', 'UNI', TRUE),
  (69010, 'Sales Returns & Refunds', 6, 69, 'Dr', 'Posting', 'PL', 'S20', 'Operating', 'Turnover (contra)', 'Customer returns reducing turnover', 'UNI', TRUE),
  (69020, 'Discounts Allowed (Settlement)', 6, 69, 'Dr', 'Posting', 'PL', 'OS', 'Operating', 'Turnover (contra)', 'Early payment discounts to customers', 'UNI', TRUE),
  (69030, 'Trade Discounts Allowed', 6, 69, 'Dr', 'Posting', 'PL', 'OS', 'Operating', 'Turnover (contra)', 'Trade discounts off list price', 'UNI', TRUE),
  (71000, 'STOCK MOVEMENT', 7, 71, 'Dr', 'Header', 'PL', NULL, 'Operating', 'Cost of Sales - Stock', 'Heading only - do not post', 'UNI', TRUE),
  (71010, 'Opening Stock - Raw Materials', 7, 71, 'Dr', 'Posting', 'PL', 'OS', 'Operating', 'Cost of Sales - Stock', 'Year start raw materials', 'UNI', TRUE),
  (71020, 'Opening Stock - WIP', 7, 71, 'Dr', 'Posting', 'PL', 'OS', 'Operating', 'Cost of Sales - Stock', 'Year start work in progress', 'UNI', TRUE),
  (71030, 'Opening Stock - Finished Goods', 7, 71, 'Dr', 'Posting', 'PL', 'OS', 'Operating', 'Cost of Sales - Stock', 'Year start finished goods', 'UNI', TRUE),
  (71040, 'Opening Stock - Goods for Resale', 7, 71, 'Dr', 'Posting', 'PL', 'OS', 'Operating', 'Cost of Sales - Stock', 'Year start resale stock', 'UNI', TRUE),
  (71910, 'Closing Stock - Raw Materials', 7, 71, 'Cr', 'Posting', 'PL', 'OS', 'Operating', 'Cost of Sales - Stock', 'Contra: year end raw materials', 'UNI', TRUE),
  (71920, 'Closing Stock - WIP', 7, 71, 'Cr', 'Posting', 'PL', 'OS', 'Operating', 'Cost of Sales - Stock', 'Contra: year end WIP', 'UNI', TRUE),
  (71930, 'Closing Stock - Finished Goods', 7, 71, 'Cr', 'Posting', 'PL', 'OS', 'Operating', 'Cost of Sales - Stock', 'Contra: year end finished goods', 'UNI', TRUE),
  (71940, 'Closing Stock - Goods for Resale', 7, 71, 'Cr', 'Posting', 'PL', 'OS', 'Operating', 'Cost of Sales - Stock', 'Contra: year end resale stock', 'UNI', TRUE),
  (72000, 'PURCHASES', 7, 72, 'Dr', 'Header', 'PL', NULL, 'Operating', 'Cost of Sales - Purchases', 'Heading only - do not post', 'UNI', TRUE),
  (72010, 'Purchases - Standard Rated (UK)', 7, 72, 'Dr', 'Posting', 'PL', 'S20', 'Operating', 'Cost of Sales - Purchases', 'UK purchases at 20% VAT', 'UNI', TRUE),
  (72020, 'Purchases - Reduced Rated (UK)', 7, 72, 'Dr', 'Posting', 'PL', 'R5', 'Operating', 'Cost of Sales - Purchases', 'UK purchases at 5% VAT', 'UNI', TRUE),
  (72030, 'Purchases - Zero Rated (UK)', 7, 72, 'Dr', 'Posting', 'PL', 'Z', 'Operating', 'Cost of Sales - Purchases', 'UK zero-rated purchases', 'UNI', TRUE),
  (72040, 'Purchases - Imports (Non-EU)', 7, 72, 'Dr', 'Posting', 'PL', 'OS', 'Operating', 'Cost of Sales - Purchases', 'Imports from outside UK & EU', 'UNI', TRUE),
  (72050, 'Purchases - EU (Reverse Charge)', 7, 72, 'Dr', 'Posting', 'PL', 'RC', 'Operating', 'Cost of Sales - Purchases', 'EU purchases under reverse charge', 'UNI', TRUE),
  (72060, 'Purchase Returns', 7, 72, 'Cr', 'Posting', 'PL', 'S20', 'Operating', 'Cost of Sales - Purchases', 'Contra: returns to suppliers', 'UNI', TRUE),
  (73000, 'DIRECT LABOUR', 7, 73, 'Dr', 'Header', 'PL', NULL, 'Operating', 'Cost of Sales - Labour', 'Heading only - do not post', 'UNI', TRUE),
  (73010, 'Direct Wages', 7, 73, 'Dr', 'Posting', 'PL', 'OS', 'Operating', 'Cost of Sales - Labour', 'Wages of production staff', 'UNI', TRUE),
  (73020, 'Direct Salaries', 7, 73, 'Dr', 'Posting', 'PL', 'OS', 'Operating', 'Cost of Sales - Labour', 'Salaries of direct staff', 'UNI', TRUE),
  (73030, 'Employer''s NI - Direct Staff', 7, 73, 'Dr', 'Posting', 'PL', 'OS', 'Operating', 'Cost of Sales - Labour', 'Employer NI for production staff', 'UNI', TRUE),
  (73040, 'Pension Contributions - Direct Staff', 7, 73, 'Dr', 'Posting', 'PL', 'OS', 'Operating', 'Cost of Sales - Labour', 'Pension for production staff', 'UNI', TRUE),
  (73050, 'Subcontractor Costs', 7, 73, 'Dr', 'Posting', 'PL', 'S20', 'Operating', 'Cost of Sales - Labour', 'Subcontractor invoices (non-CIS)', 'UNI', TRUE),
  (73060, 'CIS Subcontractor Payments', 7, 73, 'Dr', 'Posting', 'PL', 'S20', 'Operating', 'Cost of Sales - Labour', 'CIS subcontractor gross payments', 'UNI', TRUE),
  (73070, 'Casual Labour', 7, 73, 'Dr', 'Posting', 'PL', 'OS', 'Operating', 'Cost of Sales - Labour', 'Casual / day labour', 'UNI', TRUE),
  (74000, 'DIRECT PRODUCTION COSTS', 7, 74, 'Dr', 'Header', 'PL', NULL, 'Operating', 'Cost of Sales - Other', 'Heading only - do not post', 'UNI', TRUE),
  (74010, 'Production Materials & Consumables', 7, 74, 'Dr', 'Posting', 'PL', 'S20', 'Operating', 'Cost of Sales - Other', 'Direct materials and consumables', 'UNI', TRUE),
  (74020, 'Direct Power & Utilities', 7, 74, 'Dr', 'Posting', 'PL', 'R5', 'Operating', 'Cost of Sales - Other', 'Production-related utilities', 'UNI', TRUE),
  (74030, 'Plant Hire (Direct)', 7, 74, 'Dr', 'Posting', 'PL', 'S20', 'Operating', 'Cost of Sales - Other', 'Hired plant for production', 'UNI', TRUE),
  (74040, 'Equipment Hire (Direct)', 7, 74, 'Dr', 'Posting', 'PL', 'S20', 'Operating', 'Cost of Sales - Other', 'Hired equipment for production', 'UNI', TRUE),
  (74050, 'Small Tools & Equipment', 7, 74, 'Dr', 'Posting', 'PL', 'S20', 'Operating', 'Cost of Sales - Other', 'Tools below capitalisation threshold', 'UNI', TRUE),
  (75000, 'CARRIAGE & FREIGHT INWARDS', 7, 75, 'Dr', 'Header', 'PL', NULL, 'Operating', 'Cost of Sales - Other', 'Heading only - do not post', 'UNI', TRUE),
  (75010, 'Carriage Inwards', 7, 75, 'Dr', 'Posting', 'PL', 'S20', 'Operating', 'Cost of Sales - Other', 'Inbound delivery on purchases', 'UNI', TRUE),
  (75020, 'Freight & Shipping (Imports)', 7, 75, 'Dr', 'Posting', 'PL', 'OS', 'Operating', 'Cost of Sales - Other', 'International freight inbound', 'UNI', TRUE),
  (75030, 'Insurance on Imports', 7, 75, 'Dr', 'Posting', 'PL', 'E', 'Operating', 'Cost of Sales - Other', 'Marine / transit insurance', 'UNI', TRUE),
  (76000, 'IMPORT DUTIES & CUSTOMS', 7, 76, 'Dr', 'Header', 'PL', NULL, 'Operating', 'Cost of Sales - Other', 'Heading only - do not post', 'UNI', TRUE),
  (76010, 'Import Duty', 7, 76, 'Dr', 'Posting', 'PL', 'OS', 'Operating', 'Cost of Sales - Other', 'HMRC import duties', 'UNI', TRUE),
  (76020, 'Customs Clearance Fees', 7, 76, 'Dr', 'Posting', 'PL', 'S20', 'Operating', 'Cost of Sales - Other', 'Customs broker / clearance', 'UNI', TRUE),
  (81000, 'STAFF COSTS (ADMINISTRATIVE)', 8, 81, 'Dr', 'Header', 'PL', NULL, 'Operating', 'Admin Expenses - Staff', 'Heading only - do not post', 'UNI', TRUE),
  (81010, 'Salaries & Wages', 8, 81, 'Dr', 'Posting', 'PL', 'OS', 'Operating', 'Admin Expenses - Staff', 'Admin staff salaries and wages', 'UNI', TRUE),
  (81020, 'Employer''s NI Contributions', 8, 81, 'Dr', 'Posting', 'PL', 'OS', 'Operating', 'Admin Expenses - Staff', 'Employer NI on admin staff', 'UNI', TRUE),
  (81030, 'Pension Contributions', 8, 81, 'Dr', 'Posting', 'PL', 'OS', 'Operating', 'Admin Expenses - Staff', 'Employer pension contributions', 'UNI', TRUE),
  (81040, 'Bonuses & Commissions', 8, 81, 'Dr', 'Posting', 'PL', 'OS', 'Operating', 'Admin Expenses - Staff', 'Discretionary bonuses and commissions', 'UNI', TRUE),
  (81050, 'Staff Training', 8, 81, 'Dr', 'Posting', 'PL', 'S20', 'Operating', 'Admin Expenses - Staff', 'Training and CPD', 'UNI', TRUE),
  (81060, 'Staff Welfare & Refreshments', 8, 81, 'Dr', 'Posting', 'PL', 'S20', 'Operating', 'Admin Expenses - Staff', 'Tea, coffee, staff lunches, welfare', 'UNI', TRUE),
  (81070, 'Recruitment Costs', 8, 81, 'Dr', 'Posting', 'PL', 'S20', 'Operating', 'Admin Expenses - Staff', 'Agency fees, advertising for staff', 'UNI', TRUE),
  (81080, 'Temporary & Agency Staff', 8, 81, 'Dr', 'Posting', 'PL', 'S20', 'Operating', 'Admin Expenses - Staff', 'Temporary worker invoices', 'UNI', TRUE),
  (81090, 'Staff Uniforms & PPE', 8, 81, 'Dr', 'Posting', 'PL', 'S20', 'Operating', 'Admin Expenses - Staff', 'Uniforms and personal protective equipment', 'UNI', TRUE),
  (81100, 'Other Staff Costs', 8, 81, 'Dr', 'Posting', 'PL', 'S20', 'Operating', 'Admin Expenses - Staff', 'Miscellaneous staff costs', 'UNI', TRUE),
  (82000, 'DIRECTORS'' REMUNERATION', 8, 82, 'Dr', 'Header', 'PL', NULL, 'Operating', 'Admin Expenses - Directors', 'Heading only - do not post', 'UNI', TRUE),
  (82010, 'Directors'' Salaries', 8, 82, 'Dr', 'Posting', 'PL', 'OS', 'Operating', 'Admin Expenses - Directors', 'Directors'' salaries', 'UNI', TRUE),
  (82020, 'Directors'' Fees', 8, 82, 'Dr', 'Posting', 'PL', 'OS', 'Operating', 'Admin Expenses - Directors', 'Non-executive director fees', 'UNI', TRUE),
  (82030, 'Directors'' Employer''s NI', 8, 82, 'Dr', 'Posting', 'PL', 'OS', 'Operating', 'Admin Expenses - Directors', 'Employer NI on directors', 'UNI', TRUE),
  (82040, 'Directors'' Pension Contributions', 8, 82, 'Dr', 'Posting', 'PL', 'OS', 'Operating', 'Admin Expenses - Directors', 'Pension contributions for directors', 'UNI', TRUE),
  (82050, 'Directors'' Benefits in Kind', 8, 82, 'Dr', 'Posting', 'PL', 'S20', 'Operating', 'Admin Expenses - Directors', 'Taxable benefits provided to directors', 'UNI', TRUE),
  (82060, 'Directors'' Expenses', 8, 82, 'Dr', 'Posting', 'PL', 'S20', 'Operating', 'Admin Expenses - Directors', 'Reimbursed business expenses', 'UNI', TRUE),
  (83000, 'PREMISES COSTS', 8, 83, 'Dr', 'Header', 'PL', NULL, 'Operating', 'Admin Expenses - Premises', 'Heading only - do not post', 'UNI', TRUE),
  (83010, 'Rent - Office / Premises', 8, 83, 'Dr', 'Posting', 'PL', 'E', 'Operating', 'Admin Expenses - Premises', 'Office and commercial rent', 'UNI', TRUE),
  (83020, 'Business Rates', 8, 83, 'Dr', 'Posting', 'PL', 'OS', 'Operating', 'Admin Expenses - Premises', 'Local authority business rates', 'UNI', TRUE),
  (83030, 'Water Rates', 8, 83, 'Dr', 'Posting', 'PL', 'OS', 'Operating', 'Admin Expenses - Premises', 'Water and sewerage charges', 'UNI', TRUE),
  (83040, 'Light & Heat (Electricity & Gas)', 8, 83, 'Dr', 'Posting', 'PL', 'R5', 'Operating', 'Admin Expenses - Premises', 'Electricity and gas (use 20% where applicable)', 'UNI', TRUE),
  (83050, 'Property Insurance', 8, 83, 'Dr', 'Posting', 'PL', 'E', 'Operating', 'Admin Expenses - Premises', 'Buildings and contents insurance', 'UNI', TRUE),
  (83060, 'Property Repairs & Maintenance', 8, 83, 'Dr', 'Posting', 'PL', 'S20', 'Operating', 'Admin Expenses - Premises', 'Repairs and minor improvements', 'UNI', TRUE),
  (83070, 'Cleaning', 8, 83, 'Dr', 'Posting', 'PL', 'S20', 'Operating', 'Admin Expenses - Premises', 'Office and premises cleaning', 'UNI', TRUE),
  (83080, 'Security', 8, 83, 'Dr', 'Posting', 'PL', 'S20', 'Operating', 'Admin Expenses - Premises', 'Security services and alarms', 'UNI', TRUE),
  (83090, 'Service Charges', 8, 83, 'Dr', 'Posting', 'PL', 'S20', 'Operating', 'Admin Expenses - Premises', 'Landlord service charges', 'UNI', TRUE),
  (83100, 'Use of Home as Office', 8, 83, 'Dr', 'Posting', 'PL', 'OS', 'Operating', 'Admin Expenses - Premises', 'Director home-office allowance', 'UNI', TRUE),
  (84000, 'MOTOR & TRAVEL', 8, 84, 'Dr', 'Header', 'PL', NULL, 'Operating', 'Admin Expenses - Motor & Travel', 'Heading only - do not post', 'UNI', TRUE),
  (84010, 'Fuel (Petrol & Diesel)', 8, 84, 'Dr', 'Posting', 'PL', 'S20', 'Operating', 'Admin Expenses - Motor & Travel', 'Fuel for company vehicles', 'UNI', TRUE),
  (84020, 'Motor Repairs & Servicing', 8, 84, 'Dr', 'Posting', 'PL', 'S20', 'Operating', 'Admin Expenses - Motor & Travel', 'Vehicle repairs and maintenance', 'UNI', TRUE),
  (84030, 'Vehicle Insurance', 8, 84, 'Dr', 'Posting', 'PL', 'E', 'Operating', 'Admin Expenses - Motor & Travel', 'Motor insurance', 'UNI', TRUE),
  (84040, 'Vehicle Road Tax & MOT', 8, 84, 'Dr', 'Posting', 'PL', 'OS', 'Operating', 'Admin Expenses - Motor & Travel', 'Road tax and MOT fees', 'UNI', TRUE),
  (84050, 'Vehicle Hire / Lease', 8, 84, 'Dr', 'Posting', 'PL', 'S20', 'Operating', 'Admin Expenses - Motor & Travel', 'Vehicle hire and operating leases', 'UNI', TRUE),
  (84060, 'Parking & Tolls', 8, 84, 'Dr', 'Posting', 'PL', 'S20', 'Operating', 'Admin Expenses - Motor & Travel', 'Parking and toll charges', 'UNI', TRUE),
  (84070, 'Train & Rail Travel', 8, 84, 'Dr', 'Posting', 'PL', 'Z', 'Operating', 'Admin Expenses - Motor & Travel', 'UK rail (passenger transport zero-rated)', 'UNI', TRUE),
  (84080, 'Flights', 8, 84, 'Dr', 'Posting', 'PL', 'Z', 'Operating', 'Admin Expenses - Motor & Travel', 'Passenger flights (zero-rated)', 'UNI', TRUE),
  (84090, 'Taxi & Local Travel', 8, 84, 'Dr', 'Posting', 'PL', 'S20', 'Operating', 'Admin Expenses - Motor & Travel', 'Taxi and local public transport', 'UNI', TRUE),
  (84100, 'Hotel & Accommodation', 8, 84, 'Dr', 'Posting', 'PL', 'S20', 'Operating', 'Admin Expenses - Motor & Travel', 'Hotels and bed-and-breakfast', 'UNI', TRUE),
  (84110, 'Overseas Travel', 8, 84, 'Dr', 'Posting', 'PL', 'OS', 'Operating', 'Admin Expenses - Motor & Travel', 'Overseas travel expenses', 'UNI', TRUE),
  (84120, 'Subsistence & Meals', 8, 84, 'Dr', 'Posting', 'PL', 'S20', 'Operating', 'Admin Expenses - Motor & Travel', 'Meals while travelling', 'UNI', TRUE),
  (84130, 'Mileage Allowance', 8, 84, 'Dr', 'Posting', 'PL', 'OS', 'Operating', 'Admin Expenses - Motor & Travel', 'HMRC-rate mileage to staff', 'UNI', TRUE),
  (85000, 'SALES & MARKETING', 8, 85, 'Dr', 'Header', 'PL', NULL, 'Operating', 'Admin Expenses - Marketing', 'Heading only - do not post', 'UNI', TRUE),
  (85010, 'Advertising - Print', 8, 85, 'Dr', 'Posting', 'PL', 'S20', 'Operating', 'Admin Expenses - Marketing', 'Print advertising', 'UNI', TRUE),
  (85020, 'Advertising - Digital / Online', 8, 85, 'Dr', 'Posting', 'PL', 'S20', 'Operating', 'Admin Expenses - Marketing', 'Google, Meta, online ads', 'UNI', TRUE),
  (85030, 'Marketing Campaigns', 8, 85, 'Dr', 'Posting', 'PL', 'S20', 'Operating', 'Admin Expenses - Marketing', 'Marketing programme costs', 'UNI', TRUE),
  (85040, 'Website Costs (Operating)', 8, 85, 'Dr', 'Posting', 'PL', 'S20', 'Operating', 'Admin Expenses - Marketing', 'Website hosting and operating costs', 'UNI', TRUE),
  (85050, 'Exhibitions & Trade Shows', 8, 85, 'Dr', 'Posting', 'PL', 'S20', 'Operating', 'Admin Expenses - Marketing', 'Exhibition stand costs', 'UNI', TRUE),
  (85060, 'Brochures & Printing', 8, 85, 'Dr', 'Posting', 'PL', 'Z', 'Operating', 'Admin Expenses - Marketing', 'Brochures, leaflets (some zero-rated)', 'UNI', TRUE),
  (85070, 'Public Relations', 8, 85, 'Dr', 'Posting', 'PL', 'S20', 'Operating', 'Admin Expenses - Marketing', 'PR agency and activity', 'UNI', TRUE),
  (85080, 'SEO & Social Media', 8, 85, 'Dr', 'Posting', 'PL', 'S20', 'Operating', 'Admin Expenses - Marketing', 'SEO services and social media management', 'UNI', TRUE),
  (85090, 'Sponsorship', 8, 85, 'Dr', 'Posting', 'PL', 'S20', 'Operating', 'Admin Expenses - Marketing', 'Event and brand sponsorship', 'UNI', TRUE),
  (85100, 'Sales Commissions (External)', 8, 85, 'Dr', 'Posting', 'PL', 'S20', 'Operating', 'Admin Expenses - Marketing', 'Commissions to external agents', 'UNI', TRUE),
  (85110, 'Customer Entertainment (Disallowable)', 8, 85, 'Dr', 'Posting', 'PL', 'S20', 'Operating', 'Admin Expenses - Marketing', 'Client entertaining (not tax deductible)', 'UNI', TRUE),
  (85120, 'Promotional Gifts', 8, 85, 'Dr', 'Posting', 'PL', 'S20', 'Operating', 'Admin Expenses - Marketing', 'Branded gifts within HMRC limits', 'UNI', TRUE),
  (86000, 'OFFICE & ADMINISTRATION', 8, 86, 'Dr', 'Header', 'PL', NULL, 'Operating', 'Admin Expenses - Office', 'Heading only - do not post', 'UNI', TRUE),
  (86010, 'Office Stationery', 8, 86, 'Dr', 'Posting', 'PL', 'S20', 'Operating', 'Admin Expenses - Office', 'Stationery and supplies', 'UNI', TRUE),
  (86020, 'Office Consumables', 8, 86, 'Dr', 'Posting', 'PL', 'S20', 'Operating', 'Admin Expenses - Office', 'Office consumables', 'UNI', TRUE),
  (86030, 'Postage & Couriers', 8, 86, 'Dr', 'Posting', 'PL', 'S20', 'Operating', 'Admin Expenses - Office', 'Postage and courier services', 'UNI', TRUE),
  (86040, 'Printing', 8, 86, 'Dr', 'Posting', 'PL', 'S20', 'Operating', 'Admin Expenses - Office', 'Printing and reprographics', 'UNI', TRUE),
  (86050, 'Subscriptions & Memberships', 8, 86, 'Dr', 'Posting', 'PL', 'S20', 'Operating', 'Admin Expenses - Office', 'Trade body subscriptions', 'UNI', TRUE),
  (86060, 'Books & Periodicals', 8, 86, 'Dr', 'Posting', 'PL', 'Z', 'Operating', 'Admin Expenses - Office', 'Books and journals', 'UNI', TRUE),
  (86070, 'General Office Expenses', 8, 86, 'Dr', 'Posting', 'PL', 'S20', 'Operating', 'Admin Expenses - Office', 'Miscellaneous office expenses', 'UNI', TRUE),
  (86080, 'Sundry Expenses', 8, 86, 'Dr', 'Posting', 'PL', 'S20', 'Operating', 'Admin Expenses - Office', 'Sundry items, no other home', 'UNI', TRUE),
  (87000, 'PROFESSIONAL FEES', 8, 87, 'Dr', 'Header', 'PL', NULL, 'Operating', 'Admin Expenses - Professional', 'Heading only - do not post', 'UNI', TRUE),
  (87010, 'Accountancy Fees', 8, 87, 'Dr', 'Posting', 'PL', 'S20', 'Operating', 'Admin Expenses - Professional', 'Accountant and bookkeeper fees', 'UNI', TRUE),
  (87020, 'Audit Fees', 8, 87, 'Dr', 'Posting', 'PL', 'S20', 'Operating', 'Admin Expenses - Professional', 'Statutory audit fees', 'UNI', TRUE),
  (87030, 'Legal Fees (Allowable)', 8, 87, 'Dr', 'Posting', 'PL', 'S20', 'Operating', 'Admin Expenses - Professional', 'Tax-allowable legal fees', 'UNI', TRUE),
  (87040, 'Legal Fees (Disallowable)', 8, 87, 'Dr', 'Posting', 'PL', 'S20', 'Operating', 'Admin Expenses - Professional', 'Capital / disallowable legal costs', 'UNI', TRUE),
  (87050, 'Consultancy Fees Paid', 8, 87, 'Dr', 'Posting', 'PL', 'S20', 'Operating', 'Admin Expenses - Professional', 'External consultant fees', 'UNI', TRUE),
  (87060, 'Tax Advisory Fees', 8, 87, 'Dr', 'Posting', 'PL', 'S20', 'Operating', 'Admin Expenses - Professional', 'Tax advisor fees', 'UNI', TRUE),
  (87070, 'Management Fees', 8, 87, 'Dr', 'Posting', 'PL', 'S20', 'Operating', 'Admin Expenses - Professional', 'Group management charges', 'UNI', TRUE),
  (87080, 'Other Professional Fees', 8, 87, 'Dr', 'Posting', 'PL', 'S20', 'Operating', 'Admin Expenses - Professional', 'Other professional services', 'UNI', TRUE),
  (88000, 'IT & COMMUNICATIONS', 8, 88, 'Dr', 'Header', 'PL', NULL, 'Operating', 'Admin Expenses - IT & Comms', 'Heading only - do not post', 'UNI', TRUE),
  (88010, 'Telephone - Landline', 8, 88, 'Dr', 'Posting', 'PL', 'S20', 'Operating', 'Admin Expenses - IT & Comms', 'Office landline charges', 'UNI', TRUE),
  (88020, 'Telephone - Mobile', 8, 88, 'Dr', 'Posting', 'PL', 'S20', 'Operating', 'Admin Expenses - IT & Comms', 'Mobile telephone charges', 'UNI', TRUE),
  (88030, 'Internet & Broadband', 8, 88, 'Dr', 'Posting', 'PL', 'S20', 'Operating', 'Admin Expenses - IT & Comms', 'Internet connectivity', 'UNI', TRUE),
  (88040, 'Software Subscriptions (SaaS)', 8, 88, 'Dr', 'Posting', 'PL', 'S20', 'Operating', 'Admin Expenses - IT & Comms', 'Monthly / annual software subscriptions', 'UNI', TRUE),
  (88050, 'Cloud Hosting & Storage', 8, 88, 'Dr', 'Posting', 'PL', 'S20', 'Operating', 'Admin Expenses - IT & Comms', 'AWS, Azure, hosting providers', 'UNI', TRUE),
  (88060, 'IT Support & Maintenance', 8, 88, 'Dr', 'Posting', 'PL', 'S20', 'Operating', 'Admin Expenses - IT & Comms', 'IT support contracts', 'UNI', TRUE),
  (88070, 'Domain & Email Hosting', 8, 88, 'Dr', 'Posting', 'PL', 'S20', 'Operating', 'Admin Expenses - IT & Comms', 'Domain registration and email', 'UNI', TRUE),
  (88080, 'Computer Consumables', 8, 88, 'Dr', 'Posting', 'PL', 'S20', 'Operating', 'Admin Expenses - IT & Comms', 'Cables, peripherals below capitalisation', 'UNI', TRUE),
  (89000, 'DEPRECIATION & AMORTISATION', 8, 89, 'Dr', 'Header', 'PL', NULL, 'Operating', 'Admin Expenses - Depreciation', 'Heading only - do not post', 'UNI', TRUE),
  (89010, 'Depreciation - Buildings', 8, 89, 'Dr', 'Posting', 'PL', 'OS', 'Operating', 'Admin Expenses - Depreciation', 'Annual buildings depreciation', 'UNI', TRUE),
  (89020, 'Depreciation - Leasehold Improvements', 8, 89, 'Dr', 'Posting', 'PL', 'OS', 'Operating', 'Admin Expenses - Depreciation', 'Annual leasehold improvements depreciation', 'UNI', TRUE),
  (89030, 'Depreciation - Plant & Machinery', 8, 89, 'Dr', 'Posting', 'PL', 'OS', 'Operating', 'Admin Expenses - Depreciation', 'Annual plant and machinery depreciation', 'UNI', TRUE),
  (89040, 'Depreciation - Motor Vehicles', 8, 89, 'Dr', 'Posting', 'PL', 'OS', 'Operating', 'Admin Expenses - Depreciation', 'Annual motor vehicle depreciation', 'UNI', TRUE),
  (89050, 'Depreciation - Fixtures & Fittings', 8, 89, 'Dr', 'Posting', 'PL', 'OS', 'Operating', 'Admin Expenses - Depreciation', 'Annual fixtures depreciation', 'UNI', TRUE),
  (89060, 'Depreciation - Office Equipment', 8, 89, 'Dr', 'Posting', 'PL', 'OS', 'Operating', 'Admin Expenses - Depreciation', 'Annual office equipment depreciation', 'UNI', TRUE),
  (89070, 'Depreciation - Computer Equipment', 8, 89, 'Dr', 'Posting', 'PL', 'OS', 'Operating', 'Admin Expenses - Depreciation', 'Annual computer equipment depreciation', 'UNI', TRUE),
  (89080, 'Amortisation - Goodwill', 8, 89, 'Dr', 'Posting', 'PL', 'OS', 'Operating', 'Admin Expenses - Depreciation', 'Annual goodwill amortisation', 'UNI', TRUE),
  (89090, 'Amortisation - Software', 8, 89, 'Dr', 'Posting', 'PL', 'OS', 'Operating', 'Admin Expenses - Depreciation', 'Annual software amortisation', 'UNI', TRUE),
  (89100, 'Amortisation - Other Intangibles', 8, 89, 'Dr', 'Posting', 'PL', 'OS', 'Operating', 'Admin Expenses - Depreciation', 'Annual other intangibles amortisation', 'UNI', TRUE),
  (89110, 'Impairment - Tangible Assets', 8, 89, 'Dr', 'Posting', 'PL', 'OS', 'Operating', 'Admin Expenses - Depreciation', 'Impairment write-downs', 'UNI', TRUE),
  (89120, 'Impairment - Intangible Assets', 8, 89, 'Dr', 'Posting', 'PL', 'OS', 'Operating', 'Admin Expenses - Depreciation', 'Intangible impairment write-downs', 'UNI', TRUE),
  (89130, 'Loss on Disposal of Fixed Assets', 8, 89, 'Dr', 'Posting', 'PL', 'OS', 'Investing', 'Admin Expenses - Depreciation', 'Loss when sale proceeds < net book value', 'UNI', TRUE),
  (91000, 'OTHER INCOME', 9, 91, 'Cr', 'Header', 'PL', NULL, 'Operating', 'Other Operating Income', 'Heading only - do not post', 'UNI', TRUE),
  (91010, 'Profit on Disposal of Fixed Assets', 9, 91, 'Cr', 'Posting', 'PL', 'OS', 'Investing', 'Other Operating Income', 'Gain when sale proceeds > net book value', 'UNI', TRUE),
  (91020, 'Insurance Claims Received', 9, 91, 'Cr', 'Posting', 'PL', 'OS', 'Operating', 'Other Operating Income', 'Insurance settlement income', 'UNI', TRUE),
  (91030, 'Compensation Received', 9, 91, 'Cr', 'Posting', 'PL', 'OS', 'Operating', 'Other Operating Income', 'Compensation receipts', 'UNI', TRUE),
  (91040, 'Grants Received (Revenue)', 9, 91, 'Cr', 'Posting', 'PL', 'OS', 'Operating', 'Other Operating Income', 'Revenue grants', 'UNI', TRUE),
  (91050, 'Sundry Income', 9, 91, 'Cr', 'Posting', 'PL', 'OS', 'Operating', 'Other Operating Income', 'Miscellaneous other income', 'UNI', TRUE),
  (92000, 'INTEREST & INVESTMENT INCOME', 9, 92, 'Cr', 'Header', 'PL', NULL, 'Operating', 'Interest Receivable', 'Heading only - do not post', 'UNI', TRUE),
  (92010, 'Bank Interest Receivable', 9, 92, 'Cr', 'Posting', 'PL', 'OS', 'Operating', 'Interest Receivable', 'Interest on bank accounts', 'UNI', TRUE),
  (92020, 'Loan Interest Receivable', 9, 92, 'Cr', 'Posting', 'PL', 'OS', 'Operating', 'Interest Receivable', 'Interest on loans made', 'UNI', TRUE),
  (92030, 'Investment Income', 9, 92, 'Cr', 'Posting', 'PL', 'OS', 'Operating', 'Interest Receivable', 'Returns on investments', 'UNI', TRUE),
  (92040, 'Dividends Received', 9, 92, 'Cr', 'Posting', 'PL', 'OS', 'Operating', 'Interest Receivable', 'Dividends from investments', 'UNI', TRUE),
  (93000, 'INTEREST & FINANCE COSTS', 9, 93, 'Dr', 'Header', 'PL', NULL, 'Operating', 'Interest Payable', 'Heading only - do not post', 'UNI', TRUE),
  (93010, 'Bank Loan Interest', 9, 93, 'Dr', 'Posting', 'PL', 'OS', 'Operating', 'Interest Payable', 'Interest on bank loans', 'UNI', TRUE),
  (93020, 'Overdraft Interest', 9, 93, 'Dr', 'Posting', 'PL', 'OS', 'Operating', 'Interest Payable', 'Interest on overdrafts', 'UNI', TRUE),
  (93030, 'Hire Purchase Interest', 9, 93, 'Dr', 'Posting', 'PL', 'OS', 'Operating', 'Interest Payable', 'Interest element of HP payments', 'UNI', TRUE),
  (93040, 'Finance Lease Interest', 9, 93, 'Dr', 'Posting', 'PL', 'OS', 'Operating', 'Interest Payable', 'Interest element of finance leases', 'UNI', TRUE),
  (93050, 'Mortgage Interest', 9, 93, 'Dr', 'Posting', 'PL', 'OS', 'Operating', 'Interest Payable', 'Mortgage interest', 'UNI', TRUE),
  (93060, 'Loan Interest to Directors / Related Parties', 9, 93, 'Dr', 'Posting', 'PL', 'OS', 'Operating', 'Interest Payable', 'Interest paid to directors / related parties', 'UNI', TRUE),
  (93070, 'Other Finance Costs', 9, 93, 'Dr', 'Posting', 'PL', 'OS', 'Operating', 'Interest Payable', 'Other interest and finance charges', 'UNI', TRUE),
  (94000, 'BANK CHARGES, FX & BAD DEBTS', 9, 94, 'Dr', 'Header', 'PL', NULL, 'Operating', 'Admin Expenses - Finance', 'Heading only - do not post', 'UNI', TRUE),
  (94010, 'Bank Charges', 9, 94, 'Dr', 'Posting', 'PL', 'E', 'Operating', 'Admin Expenses - Finance', 'Bank account fees', 'UNI', TRUE),
  (94020, 'Payment Gateway Charges', 9, 94, 'Dr', 'Posting', 'PL', 'E', 'Operating', 'Admin Expenses - Finance', 'Stripe / PayPal / merchant fees', 'UNI', TRUE),
  (94030, 'Card Processing Fees', 9, 94, 'Dr', 'Posting', 'PL', 'E', 'Operating', 'Admin Expenses - Finance', 'Card terminal and processing fees', 'UNI', TRUE),
  (94040, 'Foreign Exchange Loss', 9, 94, 'Dr', 'Posting', 'PL', 'OS', 'Operating', 'Admin Expenses - Finance', 'Realised and unrealised FX losses', 'UNI', TRUE),
  (94050, 'Foreign Exchange Gain', 9, 94, 'Cr', 'Posting', 'PL', 'OS', 'Operating', 'Admin Expenses - Finance', 'Realised and unrealised FX gains (contra)', 'UNI', TRUE),
  (94060, 'Bad Debts Written Off', 9, 94, 'Dr', 'Posting', 'PL', 'OS', 'Operating', 'Admin Expenses - Finance', 'Specific bad debt write-offs', 'UNI', TRUE),
  (94070, 'Bad Debt Provision Movement (P&L)', 9, 94, 'Dr', 'Posting', 'PL', 'OS', 'Operating', 'Admin Expenses - Finance', 'P&L charge for change in doubtful debt provision', 'UNI', TRUE),
  (95000, 'EXCEPTIONAL ITEMS', 9, 95, 'Dr', 'Header', 'PL', NULL, 'Operating', 'Exceptional Items', 'Heading only - do not post', 'UNI', TRUE),
  (95010, 'Restructuring Costs', 9, 95, 'Dr', 'Posting', 'PL', 'S20', 'Operating', 'Exceptional Items', 'One-off restructuring expenses', 'UNI', TRUE),
  (95020, 'Exceptional Items - Income', 9, 95, 'Cr', 'Posting', 'PL', 'OS', 'Operating', 'Exceptional Items', 'Exceptional gains', 'UNI', TRUE),
  (95030, 'Exceptional Items - Costs', 9, 95, 'Dr', 'Posting', 'PL', 'OS', 'Operating', 'Exceptional Items', 'Exceptional losses', 'UNI', TRUE),
  (95040, 'Profit / Loss on Termination of Operation', 9, 95, 'Dr', 'Posting', 'PL', 'OS', 'Operating', 'Exceptional Items', 'Discontinued operation result', 'UNI', TRUE),
  (96000, 'TAXATION', 9, 96, 'Dr', 'Header', 'PL', NULL, 'Operating', 'Taxation', 'Heading only - do not post', 'UNI', TRUE),
  (96010, 'Corporation Tax (Current Year)', 9, 96, 'Dr', 'Posting', 'PL', 'OS', 'Operating', 'Taxation', 'Current year CT charge', 'UNI', TRUE),
  (96020, 'Corporation Tax (Prior Year Adjustment)', 9, 96, 'Dr', 'Posting', 'PL', 'OS', 'Operating', 'Taxation', 'Prior year CT adjustments', 'UNI', TRUE),
  (96030, 'Deferred Tax Charge / Credit', 9, 96, 'Dr', 'Posting', 'PL', 'OS', 'Operating', 'Taxation', 'Movement in deferred tax', 'UNI', TRUE),
  (96040, 'Withholding Tax Suffered', 9, 96, 'Dr', 'Posting', 'PL', 'OS', 'Operating', 'Taxation', 'Overseas tax suffered on income', 'UNI', TRUE),
  (99000, 'SUSPENSE & CONTROL', 9, 99, 'Dr', 'Header', 'PL', NULL, 'N/A', 'Suspense', 'Heading only - do not post', 'UNI', TRUE),
  (99010, 'Suspense Account', 9, 99, 'Dr', 'Posting', 'PL', 'OS', 'N/A', 'Suspense', 'Unidentified transactions - must be cleared', 'UNI', TRUE),
  (99020, 'Mispostings / Unallocated', 9, 99, 'Dr', 'Posting', 'PL', 'OS', 'N/A', 'Suspense', 'Items pending reallocation', 'UNI', TRUE),
  (99030, 'Opening Balance Equity', 9, 99, 'Cr', 'Posting', 'PL', 'OS', 'N/A', 'Suspense', 'Used when migrating in opening balances', 'UNI', TRUE),
  (99040, 'Rounding Account', 9, 99, 'Dr', 'Posting', 'PL', 'OS', 'N/A', 'Suspense', 'Rounding differences', 'UNI', TRUE),
  (13070, 'Site Plant & Heavy Equipment — Cost', 1, 13, 'Dr', 'Posting', 'BS', 'S20', 'Investing', 'Tangible Fixed Assets', 'Site-based plant, scaffolding, formwork.', 'CN', TRUE),
  (13080, 'Small Tools & Site Consumables — Capitalised', 1, 13, 'Dr', 'Posting', 'BS', 'S20', 'Investing', 'Tangible Fixed Assets', 'Capitalised small tools above de minimis threshold.', 'CN', TRUE),
  (16070, 'Common Investment Fund Units', 1, 16, 'Dr', 'Posting', 'BS', 'OS', 'Investing', 'Investments', 'Holdings in CIFs / CAIFs operated under the Charities Act.', 'CH', TRUE),
  (16080, 'Permanent Endowment — Investment Portfolio', 1, 16, 'Dr', 'Posting', 'BS', 'OS', 'Investing', 'Investments', 'Investments held within permanent endowment funds.', 'CH', TRUE),
  (16090, 'Total Return — Trust for Investment', 1, 16, 'Dr', 'Posting', 'BS', 'OS', 'Investing', 'Investments', 'Endowment investments under total return approach (CC14).', 'CH', TRUE),
  (17000, 'HERITAGE & CHARITABLE ASSETS', 1, 17, 'Dr', 'Header', 'BS', NULL, 'Investing', 'Heritage Assets', 'Heading only — do not post', 'CH', TRUE),
  (17010, 'Heritage Assets — Cost', 1, 17, 'Dr', 'Posting', 'BS', 'OS', 'Investing', 'Heritage Assets', 'Historic, artistic or scientific assets held for preservation (SORP 18). Not normally depreciated.', 'CH', TRUE),
  (17020, 'Functional Property — Charity Use', 1, 17, 'Dr', 'Posting', 'BS', 'OS', 'Investing', 'Tangible Fixed Assets', 'Property used directly for charitable activities (e.g. parish hall, day centre).', 'CH', TRUE),
  (17030, 'Donated Tangible Fixed Assets — at Valuation', 1, 17, 'Dr', 'Posting', 'BS', 'OS', 'Investing', 'Tangible Fixed Assets', 'Assets gifted to the charity, recognised at fair value on receipt (SORP 6).', 'CH', TRUE),
  (17040, 'Programme-Related Investments', 1, 17, 'Dr', 'Posting', 'BS', 'OS', 'Investing', 'Investments', 'Investments made to further the charity''s purposes rather than for financial return.', 'CH', TRUE),
  (17050, 'Mixed-Motive Investments', 1, 17, 'Dr', 'Posting', 'BS', 'OS', 'Investing', 'Investments', 'Investments held partly for charitable purpose and partly for financial return.', 'CH', TRUE),
  (17910, 'Heritage Assets — Impairment', 1, 17, 'Cr', 'Posting', 'BS', 'OS', 'Investing', 'Heritage Assets', 'Provisions for impairment of heritage assets.', 'CH', TRUE),
  (17920, 'Functional Property — Accumulated Depreciation', 1, 17, 'Cr', 'Posting', 'BS', 'OS', 'Investing', 'Tangible Fixed Assets', 'Depreciation on functional charity property.', 'CH', TRUE),
  (18000, 'BIOLOGICAL ASSETS — BEARER', 1, 18, 'Dr', 'Header', 'BS', NULL, 'Investing', 'Biological Assets', 'Heading only — do not post', 'AG', TRUE),
  (18010, 'Breeding Livestock — Cattle (at Cost or FV)', 1, 18, 'Dr', 'Posting', 'BS', 'OS', 'Investing', 'Biological Assets', 'Breeding herd — accounted under FRS 102 s.34 (cost or fair value model).', 'AG', TRUE),
  (18020, 'Breeding Livestock — Sheep', 1, 18, 'Dr', 'Posting', 'BS', 'OS', 'Investing', 'Biological Assets', 'Breeding flock.', 'AG', TRUE),
  (18030, 'Breeding Livestock — Other', 1, 18, 'Dr', 'Posting', 'BS', 'OS', 'Investing', 'Biological Assets', 'Pigs, goats, other breeding stock.', 'AG', TRUE),
  (18040, 'Bearer Plants — Orchards & Vineyards', 1, 18, 'Dr', 'Posting', 'BS', 'OS', 'Investing', 'Biological Assets', 'Mature bearer plants (accounted as PPE under FRS 102 s.17 once productive).', 'AG', TRUE),
  (18050, 'Single Payment / BPS Entitlements', 1, 18, 'Dr', 'Posting', 'BS', 'OS', 'Investing', 'Intangible Assets', 'Tradable agricultural subsidy entitlements.', 'AG', TRUE),
  (18910, 'Biological Assets — Accumulated Depreciation/FV adj', 1, 18, 'Cr', 'Posting', 'BS', 'OS', 'Investing', 'Biological Assets', 'Cost-model depreciation or fair-value adjustment contra.', 'AG', TRUE),
  (21070, 'Construction Work-in-Progress (Contract WIP)', 2, 21, 'Dr', 'Posting', 'BS', NULL, 'Operating', 'Stocks', 'Costs incurred plus recognised profit less progress billings.', 'CN', TRUE),
  (21080, 'Long-Term Contract Balances — Amounts Recoverable', 2, 21, 'Dr', 'Posting', 'BS', NULL, 'Operating', 'Stocks', 'FRS 102 Section 23 — amounts recoverable on contracts.', 'CN', TRUE),
  (21090, 'Stock — Food', 2, 21, 'Dr', 'Posting', 'BS', NULL, 'Operating', 'Stocks', 'Raw food and prepared food held in kitchen and stores.', 'HP', TRUE),
  (21091, 'Stock — Beverage (Wet)', 2, 21, 'Dr', 'Posting', 'BS', NULL, 'Operating', 'Stocks', 'Wines, spirits, beers, soft drinks.', 'HP', TRUE),
  (21092, 'Stock — Non-Consumables (Linen, China, Glass)', 2, 21, 'Dr', 'Posting', 'BS', NULL, 'Operating', 'Stocks', 'Restaurant operating supplies.', 'HP', TRUE),
  (21100, 'Stock — Growing Crops (Field, Pre-Harvest)', 2, 21, 'Dr', 'Posting', 'BS', 'Z', 'Operating', 'Stocks', 'Crops in the ground at year-end, valued under FRS 102 s.34.', 'AG', TRUE),
  (21110, 'Stock — Harvested Produce', 2, 21, 'Dr', 'Posting', 'BS', 'Z', 'Operating', 'Stocks', 'Grain, hay, silage, harvested crops in store.', 'AG', TRUE),
  (21120, 'Stock — Trading Livestock (for Resale)', 2, 21, 'Dr', 'Posting', 'BS', 'Z', 'Operating', 'Stocks', 'Livestock held for resale (consumable biological assets).', 'AG', TRUE),
  (21130, 'Stock — Feed, Seed, Fertiliser, Agrochemicals', 2, 21, 'Dr', 'Posting', 'BS', 'Z', 'Operating', 'Stocks', 'Inputs held at year-end.', 'AG', TRUE),
  (22075, 'Retentions Receivable — Due Within One Year', 2, 22, 'Dr', 'Posting', 'BS', 'OS', 'Operating', 'Debtors', 'Retention monies due back from customers within 12 months.', 'CN', TRUE),
  (22080, 'Applications for Payment — Uncertified', 2, 22, 'Dr', 'Posting', 'BS', 'OS', 'Operating', 'Debtors', 'Interim applications submitted but not yet certified.', 'CN', TRUE),
  (22091, 'Care Fees Receivable — Local Authority', 2, 22, 'Dr', 'Posting', 'BS', 'EX', 'Operating', 'Debtors', 'Sub-control for local authority funded service users.', 'CR', TRUE),
  (22092, 'Care Fees Receivable — NHS / CCG / ICB', 2, 22, 'Dr', 'Posting', 'BS', 'EX', 'Operating', 'Debtors', 'NHS Continuing Healthcare and ICB-funded placements.', 'CR', TRUE),
  (22093, 'Care Fees Receivable — Private / Self-Funded', 2, 22, 'Dr', 'Posting', 'BS', 'EX', 'Operating', 'Debtors', 'Private fee-paying residents / clients.', 'CR', TRUE),
  (22094, 'Care Fees Receivable — Top-Up (Third-Party)', 2, 22, 'Dr', 'Posting', 'BS', 'EX', 'Operating', 'Debtors', 'Third-party top-up payments from families.', 'CR', TRUE),
  (22095, 'Direct Payments / Personal Budgets Receivable', 2, 22, 'Dr', 'Posting', 'BS', 'EX', 'Operating', 'Debtors', 'Service users using direct payments / personal budgets.', 'CR', TRUE),
  (26055, 'CIS Tax Suffered (Subcontractor)', 2, 26, 'Dr', 'Posting', 'BS', 'OS', 'Operating', 'Debtors', 'CIS deducted by contractor from amounts paid to this business.', 'CN', TRUE),
  (26060, 'Domestic Reverse Charge — Input VAT', 2, 26, 'Dr', 'Posting', 'BS', 'DRC', 'Operating', 'Debtors', 'Self-accounted input VAT under DRC for construction services.', 'CN', TRUE),
  (27000, 'CHARITY DEBTORS & RECEIVABLES', 2, 27, 'Dr', 'Header', 'BS', NULL, 'Operating', 'Debtors', 'Heading only — do not post', 'CH', TRUE),
  (27010, 'Grants Receivable — Restricted', 2, 27, 'Dr', 'Posting', 'BS', 'OS', 'Operating', 'Debtors', 'Grants awarded but not yet received, for restricted purposes.', 'CH', TRUE),
  (27020, 'Grants Receivable — Unrestricted', 2, 27, 'Dr', 'Posting', 'BS', 'OS', 'Operating', 'Debtors', 'Grants awarded but not yet received, for general charitable use.', 'CH', TRUE),
  (27030, 'Legacies Receivable', 2, 27, 'Dr', 'Posting', 'BS', 'OS', 'Operating', 'Debtors', 'Legacies where entitlement, probability of receipt and reliable measurement are met (SORP 5).', 'CH', TRUE),
  (27040, 'Gift Aid Receivable from HMRC', 2, 27, 'Dr', 'Posting', 'BS', 'OS', 'Operating', 'Debtors', 'Gift Aid claim submitted or claimable on eligible donations.', 'CH', TRUE),
  (27050, 'Pledged Donations Receivable', 2, 27, 'Dr', 'Posting', 'BS', 'OS', 'Operating', 'Debtors', 'Pledges from donors meeting the SORP recognition criteria.', 'CH', TRUE),
  (27060, 'Trading Subsidiary — Intercompany Debtor', 2, 27, 'Dr', 'Posting', 'BS', 'OS', 'Operating', 'Debtors', 'Amounts due from non-primary purpose trading subsidiary.', 'CH', TRUE),
  (27070, 'Restricted Cash — Designated Bank Account', 2, 27, 'Dr', 'Posting', 'BS', 'OS', 'Operating', 'Cash at Bank', 'Bank balances held for specific restricted funds (sub-ledger to 24xxx).', 'CH', TRUE),
  (32070, 'Resident Personal Allowance — Held in Trust', 3, 32, 'Cr', 'Posting', 'BS', 'OS', 'Operating', 'Creditors', 'Resident personal allowances held by the home (CQC regulated activity).', 'CR', TRUE),
  (33070, 'Retentions Payable to Subcontractors — < 1 Year', 3, 33, 'Cr', 'Posting', 'BS', 'OS', 'Operating', 'Creditors', 'Retention monies withheld from subcontractors, due within 12 months.', 'CN', TRUE),
  (33080, 'Payments on Account from Customers', 3, 33, 'Cr', 'Posting', 'BS', 'OS', 'Operating', 'Creditors', 'Customer payments on account in excess of work certified.', 'CN', TRUE),
  (33090, 'Long-Term Contract — Excess Billings Over Costs', 3, 33, 'Cr', 'Posting', 'BS', 'OS', 'Operating', 'Creditors', 'FRS 102 — billings to date exceed costs plus recognised profit.', 'CN', TRUE),
  (34070, 'CIS Payable to HMRC', 3, 34, 'Cr', 'Posting', 'BS', 'OS', 'Operating', 'Creditors', 'CIS deductions withheld from subcontractors, due to HMRC.', 'CN', TRUE),
  (34080, 'Domestic Reverse Charge — Output VAT', 3, 34, 'Cr', 'Posting', 'BS', 'DRC', 'Operating', 'Creditors', 'Self-accounted output VAT under DRC.', 'CN', TRUE),
  (34090, 'Tronc — PAYE Payable', 3, 34, 'Cr', 'Posting', 'BS', NULL, 'Operating', 'Creditors', 'PAYE on tronc distributions (no NI under approved scheme).', 'HP', TRUE),
  (37090, 'Tronc Clearing Account', 3, 37, 'Cr', 'Posting', 'BS', NULL, 'Operating', 'Creditors', 'Service charges and tips collected pending distribution by troncmaster.', 'HP', TRUE),
  (39000, 'RESTRICTED & DEFERRED CHARITY LIABILITIES', 3, 39, 'Cr', 'Header', 'BS', NULL, 'Operating', 'Creditors', 'Heading only — do not post', 'CH', TRUE),
  (39010, 'Grants Received in Advance — Restricted', 3, 39, 'Cr', 'Posting', 'BS', 'OS', 'Operating', 'Creditors', 'Restricted grants received but where conditions of entitlement not yet met (SORP 5.16).', 'CH', TRUE),
  (39020, 'Grants Payable — Committed but Unpaid', 3, 39, 'Cr', 'Posting', 'BS', 'OS', 'Operating', 'Creditors', 'Grants the charity has committed to pay to beneficiaries / partner bodies.', 'CH', TRUE),
  (39030, 'Deferred Income — Membership & Subscriptions', 3, 39, 'Cr', 'Posting', 'BS', 'OS', 'Operating', 'Creditors', 'Subscriptions covering future periods.', 'CH', TRUE),
  (39040, 'Deferred Income — Event & Programme Fees', 3, 39, 'Cr', 'Posting', 'BS', 'OS', 'Operating', 'Creditors', 'Fees received in advance of the related charitable activity.', 'CH', TRUE),
  (39050, 'Trading Subsidiary — Intercompany Creditor', 3, 39, 'Cr', 'Posting', 'BS', 'OS', 'Operating', 'Creditors', 'Amounts owed to non-primary purpose trading subsidiary.', 'CH', TRUE),
  (46000, 'RETENTIONS PAYABLE — LONG-TERM', 4, 46, 'Cr', 'Header', 'BS', NULL, 'Operating', 'Creditors > 1 Year', 'Heading only — do not post', 'CN', TRUE),
  (46010, 'Retentions Payable to Subcontractors — > 1 Year', 4, 46, 'Cr', 'Posting', 'BS', 'OS', 'Operating', 'Creditors > 1 Year', 'Retentions held beyond 12 months pending defects period.', 'CN', TRUE),
  (57000, 'UNRESTRICTED FUNDS', 5, 57, 'Cr', 'Header', 'BS', NULL, NULL, 'Reserves', 'Heading only — do not post', 'CH', TRUE),
  (57010, 'General (Unrestricted) Fund — Brought Forward', 5, 57, 'Cr', 'Posting', 'BS', NULL, NULL, 'Reserves', 'Free reserves available for any charitable purpose.', 'CH', TRUE),
  (57020, 'General (Unrestricted) Fund — Movement This Year', 5, 57, 'Cr', 'Posting', 'BS', NULL, NULL, 'Reserves', 'Surplus or deficit on unrestricted funds for the year.', 'CH', TRUE),
  (57030, 'Designated Fund — Property & Premises', 5, 57, 'Cr', 'Posting', 'BS', NULL, NULL, 'Reserves', 'Trustee-designated funds set aside for property maintenance / expansion.', 'CH', TRUE),
  (57040, 'Designated Fund — Programme Development', 5, 57, 'Cr', 'Posting', 'BS', NULL, NULL, 'Reserves', 'Trustee-designated funds for specified future programmes.', 'CH', TRUE),
  (57050, 'Designated Fund — Risk Reserve', 5, 57, 'Cr', 'Posting', 'BS', NULL, NULL, 'Reserves', 'Trustee-designated risk / contingency reserve.', 'CH', TRUE),
  (58000, 'RESTRICTED INCOME FUNDS', 5, 58, 'Cr', 'Header', 'BS', NULL, NULL, 'Reserves', 'Heading only — do not post', 'CH', TRUE),
  (58010, 'Restricted Fund — Brought Forward', 5, 58, 'Cr', 'Posting', 'BS', NULL, NULL, 'Reserves', 'Opening balances on restricted funds.', 'CH', TRUE),
  (58020, 'Restricted Fund — Movement This Year', 5, 58, 'Cr', 'Posting', 'BS', NULL, NULL, 'Reserves', 'Net movement on restricted funds in the year.', 'CH', TRUE),
  (58030, 'Restricted Fund — Building & Capital Projects', 5, 58, 'Cr', 'Posting', 'BS', NULL, NULL, 'Reserves', 'Funds given for capital expenditure on buildings.', 'CH', TRUE),
  (58040, 'Restricted Fund — Specific Programmes', 5, 58, 'Cr', 'Posting', 'BS', NULL, NULL, 'Reserves', 'Funds restricted to named programmes or services.', 'CH', TRUE),
  (58050, 'Restricted Fund — Hardship / Beneficiary Relief', 5, 58, 'Cr', 'Posting', 'BS', NULL, NULL, 'Reserves', 'Funds for grants / relief to individual beneficiaries.', 'CH', TRUE),
  (59000, 'ENDOWMENT FUNDS', 5, 59, 'Cr', 'Header', 'BS', NULL, NULL, 'Reserves', 'Heading only — do not post', 'CH', TRUE),
  (59010, 'Permanent Endowment — Brought Forward', 5, 59, 'Cr', 'Posting', 'BS', NULL, NULL, 'Reserves', 'Capital that cannot be spent — only income may be applied.', 'CH', TRUE),
  (59020, 'Permanent Endowment — Movement This Year', 5, 59, 'Cr', 'Posting', 'BS', NULL, NULL, 'Reserves', 'Gains / losses on permanent endowment capital.', 'CH', TRUE),
  (59030, 'Expendable Endowment — Brought Forward', 5, 59, 'Cr', 'Posting', 'BS', NULL, NULL, 'Reserves', 'Capital that trustees may convert to income.', 'CH', TRUE),
  (59040, 'Expendable Endowment — Movement This Year', 5, 59, 'Cr', 'Posting', 'BS', NULL, NULL, 'Reserves', 'Gains / losses / releases on expendable endowment.', 'CH', TRUE),
  (59050, 'Total Return Reserve — Unapplied Total Return', 5, 59, 'Cr', 'Posting', 'BS', NULL, NULL, 'Reserves', 'Unapplied total return on endowment under CC14.', 'CH', TRUE),
  (61075, 'Food Sales — Restaurant', 6, 61, 'Cr', 'Posting', 'PL', 'S20', 'Operating', 'Turnover', 'Restaurant food sales (eat in & takeaway hot food).', 'HP', TRUE),
  (61080, 'Beverage Sales — Wet', 6, 61, 'Cr', 'Posting', 'PL', 'S20', 'Operating', 'Turnover', 'Alcoholic and soft drink sales.', 'HP', TRUE),
  (61081, 'Crop Sales — Cereals & Combinable Crops', 6, 61, 'Cr', 'Posting', 'PL', 'Z', 'Operating', 'Turnover', 'Wheat, barley, oilseed, pulses.', 'AG', TRUE),
  (61082, 'Crop Sales — Horticulture & Fruit', 6, 61, 'Cr', 'Posting', 'PL', 'Z', 'Operating', 'Turnover', 'Fruit, vegetables, salad crops.', 'AG', TRUE),
  (61083, 'Livestock Sales — Cattle (Finished/Cull)', 6, 61, 'Cr', 'Posting', 'PL', 'Z', 'Operating', 'Turnover', 'Sales of finished cattle and cull cows.', 'AG', TRUE),
  (61084, 'Livestock Sales — Sheep & Lambs', 6, 61, 'Cr', 'Posting', 'PL', 'Z', 'Operating', 'Turnover', 'Sales of lambs, hoggets, cull sheep.', 'AG', TRUE),
  (61085, 'Milk Sales', 6, 61, 'Cr', 'Posting', 'PL', 'Z', 'Operating', 'Turnover', 'Liquid milk sales to processor / direct.', 'AG', TRUE),
  (61086, 'Wool, Hides & By-Product Sales', 6, 61, 'Cr', 'Posting', 'PL', 'Z', 'Operating', 'Turnover', 'Wool, hides, manure sales.', 'AG', TRUE),
  (61090, 'Takeaway Cold Food Sales (Zero-Rated)', 6, 61, 'Cr', 'Posting', 'PL', 'Z', 'Operating', 'Turnover', 'Cold takeaway food at zero rate.', 'HP', TRUE),
  (62075, 'Contract Revenue — Long-Term Contracts', 6, 62, 'Cr', 'Posting', 'PL', 'S20', 'Operating', 'Turnover', 'Revenue recognised by stage of completion (FRS 102 s.23).', 'CN', TRUE),
  (62080, 'Contract Revenue — Variations & Claims', 6, 62, 'Cr', 'Posting', 'PL', 'S20', 'Operating', 'Turnover', 'Revenue from agreed variations and claims.', 'CN', TRUE),
  (62090, 'Contract Revenue — Domestic Reverse Charge Sales', 6, 62, 'Cr', 'Posting', 'PL', 'DRC', 'Operating', 'Turnover', 'Construction sales subject to DRC (customer accounts for VAT).', 'CN', TRUE),
  (62091, 'Service Charge Income — Discretionary', 6, 62, 'Cr', 'Posting', 'PL', 'EX', 'Operating', 'Turnover', 'Discretionary service charge (not consideration for VAT).', 'HP', TRUE),
  (62100, 'Care Fees — Local Authority Block Contract', 6, 62, 'Cr', 'Posting', 'PL', 'EX', 'Operating', 'Turnover', 'Block-contracted care provision.', 'CR', TRUE),
  (62110, 'Care Fees — Local Authority Spot Purchase', 6, 62, 'Cr', 'Posting', 'PL', 'EX', 'Operating', 'Turnover', 'Spot-purchased placements.', 'CR', TRUE),
  (62120, 'Care Fees — NHS Continuing Healthcare', 6, 62, 'Cr', 'Posting', 'PL', 'EX', 'Operating', 'Turnover', 'Fully NHS-funded care.', 'CR', TRUE),
  (62130, 'Care Fees — NHS Funded Nursing Care (FNC)', 6, 62, 'Cr', 'Posting', 'PL', 'EX', 'Operating', 'Turnover', 'Nursing element of fees paid by NHS.', 'CR', TRUE),
  (62140, 'Care Fees — Private / Self-Funded', 6, 62, 'Cr', 'Posting', 'PL', 'EX', 'Operating', 'Turnover', 'Privately funded residents / clients.', 'CR', TRUE),
  (62150, 'Care Fees — Top-Up Payments', 6, 62, 'Cr', 'Posting', 'PL', 'EX', 'Operating', 'Turnover', 'Third-party top-up income.', 'CR', TRUE),
  (62160, 'Domiciliary Care — Hourly Visits', 6, 62, 'Cr', 'Posting', 'PL', 'EX', 'Operating', 'Turnover', 'Income from home care visits.', 'CR', TRUE),
  (62170, 'Supported Living — Hours Delivered', 6, 62, 'Cr', 'Posting', 'PL', 'EX', 'Operating', 'Turnover', 'Supported living support hours.', 'CR', TRUE),
  (64070, 'Room Hire & Function Income', 6, 64, 'Cr', 'Posting', 'PL', 'S20', 'Operating', 'Turnover', 'Hire of private dining rooms, function income.', 'HP', TRUE),
  (64080, 'Cover Charge Income', 6, 64, 'Cr', 'Posting', 'PL', 'S20', 'Operating', 'Turnover', 'Per-cover charge (track covers in stats module).', 'HP', TRUE),
  (64090, 'Accommodation Income (if applicable)', 6, 64, 'Cr', 'Posting', 'PL', 'S20', 'Operating', 'Turnover', 'Room nights for hospitality businesses operating accommodation.', 'HP', TRUE),
  (64091, 'BPS / Delinked / SFI Payments', 6, 64, 'Cr', 'Posting', 'PL', 'OS', 'Operating', 'Turnover', 'Direct subsidy payments (Basic Payment / Delinked / Sustainable Farming Incentive).', 'AG', TRUE),
  (64092, 'Countryside Stewardship / Environmental Grants', 6, 64, 'Cr', 'Posting', 'PL', 'OS', 'Operating', 'Turnover', 'Agri-environment scheme income.', 'AG', TRUE),
  (64093, 'Diversification Income — Holiday Lets / Glamping', 6, 64, 'Cr', 'Posting', 'PL', 'S20', 'Operating', 'Turnover', 'Income from diversified farm enterprises.', 'AG', TRUE),
  (64094, 'Contracting Work for Other Farms', 6, 64, 'Cr', 'Posting', 'PL', 'S20', 'Operating', 'Turnover', 'Agricultural contracting income (combining, baling, spraying).', 'AG', TRUE),
  (64100, 'Ancillary Services — Hairdressing, Chiropody', 6, 64, 'Cr', 'Posting', 'PL', 'EX', 'Operating', 'Turnover', 'On-site ancillary services charged to residents.', 'CR', TRUE),
  (66000, 'DONATIONS & LEGACIES', 6, 66, 'Cr', 'Header', 'PL', NULL, 'Operating', 'Donations & Legacies', 'Heading only — do not post', 'CH', TRUE),
  (66010, 'Donations — Individual (Cash & Card)', 6, 66, 'Cr', 'Posting', 'PL', 'OS', 'Operating', 'Donations & Legacies', 'Cash donations from individuals (collection plates, online, standing orders).', 'CH', TRUE),
  (66020, 'Donations — Corporate & Trust', 6, 66, 'Cr', 'Posting', 'PL', 'OS', 'Operating', 'Donations & Legacies', 'Gifts from companies and grant-making trusts.', 'CH', TRUE),
  (66030, 'Gift Aid Reclaimed', 6, 66, 'Cr', 'Posting', 'PL', 'OS', 'Operating', 'Donations & Legacies', 'Tax recovered from HMRC on eligible donations.', 'CH', TRUE),
  (66040, 'Legacies Recognised', 6, 66, 'Cr', 'Posting', 'PL', 'OS', 'Operating', 'Donations & Legacies', 'Income from legacies meeting SORP recognition criteria.', 'CH', TRUE),
  (66050, 'Donated Goods, Services & Facilities', 6, 66, 'Cr', 'Posting', 'PL', 'OS', 'Operating', 'Donations & Legacies', 'Fair value of donated goods, services and facilities (SORP 6).', 'CH', TRUE),
  (66060, 'Membership Subscriptions (Donative element)', 6, 66, 'Cr', 'Posting', 'PL', 'EX', 'Operating', 'Donations & Legacies', 'Subscription income where substantially a donation.', 'CH', TRUE),
  (66070, 'Sponsorship & Fundraising Pledges', 6, 66, 'Cr', 'Posting', 'PL', 'OS', 'Operating', 'Donations & Legacies', 'Sponsorship pledges and fundraising commitments.', 'CH', TRUE),
  (67000, 'CHARITABLE ACTIVITIES — INCOME', 6, 67, 'Cr', 'Header', 'PL', NULL, 'Operating', 'Charitable Activities', 'Heading only — do not post', 'CH', TRUE),
  (67010, 'Grant Income — Restricted', 6, 67, 'Cr', 'Posting', 'PL', 'OS', 'Operating', 'Charitable Activities', 'Grants where the donor specifies the use.', 'CH', TRUE),
  (67020, 'Grant Income — Unrestricted', 6, 67, 'Cr', 'Posting', 'PL', 'OS', 'Operating', 'Charitable Activities', 'Grants without restriction on use.', 'CH', TRUE),
  (67030, 'Statutory Grants & Service-Level Agreements', 6, 67, 'Cr', 'Posting', 'PL', 'OS', 'Operating', 'Charitable Activities', 'Income from local authorities, NHS, central government under SLAs.', 'CH', TRUE),
  (67040, 'Contract Income — Performance-Related', 6, 67, 'Cr', 'Posting', 'PL', 'S20', 'Operating', 'Charitable Activities', 'Income from contracts where charity delivers a specified service.', 'CH', TRUE),
  (67050, 'Beneficiary Fees & Contributions', 6, 67, 'Cr', 'Posting', 'PL', 'EX', 'Operating', 'Charitable Activities', 'Fees paid by service users where charging is part of the charitable purpose.', 'CH', TRUE),
  (67060, 'Programme & Event Income — Charitable', 6, 67, 'Cr', 'Posting', 'PL', 'EX', 'Operating', 'Charitable Activities', 'Income from courses, retreats, training delivered as part of charitable purposes.', 'CH', TRUE),
  (68000, 'OTHER TRADING & FUNDRAISING INCOME', 6, 68, 'Cr', 'Header', 'PL', NULL, 'Operating', 'Other Trading Activities', 'Heading only — do not post', 'CH', TRUE),
  (68010, 'Trading Subsidiary — Gift Aid Transfer', 6, 68, 'Cr', 'Posting', 'PL', 'OS', 'Operating', 'Other Trading Activities', 'Profits gifted from non-primary purpose trading subsidiary.', 'CH', TRUE),
  (68020, 'Charity Shop Income', 6, 68, 'Cr', 'Posting', 'PL', 'S20', 'Operating', 'Other Trading Activities', 'Retail sales (donated goods are zero-rated; bought-in goods are standard / mixed).', 'CH', TRUE),
  (68030, 'Lottery, Raffles & Tombola Income', 6, 68, 'Cr', 'Posting', 'PL', 'OS', 'Operating', 'Other Trading Activities', 'Net income from charity lotteries (Gambling Act 2005).', 'CH', TRUE),
  (68040, 'Fundraising Events — Income', 6, 68, 'Cr', 'Posting', 'PL', 'EX', 'Operating', 'Other Trading Activities', 'Gross income from events (VAT exemption applies where conditions met).', 'CH', TRUE),
  (68050, 'Investment Property Rental Income', 6, 68, 'Cr', 'Posting', 'PL', 'EX', 'Operating', 'Investment Income', 'Rental income from investment properties held by the charity.', 'CH', TRUE),
  (72070, 'Purchases — Food', 7, 72, 'Dr', 'Posting', 'PL', 'Z', 'Operating', 'Cost of Sales', 'Food purchases (most zero-rated; some standard).', 'HP', TRUE),
  (72080, 'Purchases — Beverage (Wet)', 7, 72, 'Dr', 'Posting', 'PL', 'S20', 'Operating', 'Cost of Sales', 'Beverage purchases.', 'HP', TRUE),
  (72090, 'Purchases — Non-Consumables (Linen, Crockery)', 7, 72, 'Dr', 'Posting', 'PL', 'S20', 'Operating', 'Cost of Sales', 'Replacement linen, glassware, crockery.', 'HP', TRUE),
  (72100, 'Seed Costs', 7, 72, 'Dr', 'Posting', 'PL', 'Z', 'Operating', 'Cost of Sales', 'Seed purchases for cropping.', 'AG', TRUE),
  (72110, 'Fertiliser & Lime', 7, 72, 'Dr', 'Posting', 'PL', 'S20', 'Operating', 'Cost of Sales', 'Fertiliser, lime and soil conditioners.', 'AG', TRUE),
  (72120, 'Agrochemicals & Sprays', 7, 72, 'Dr', 'Posting', 'PL', 'S20', 'Operating', 'Cost of Sales', 'Herbicides, fungicides, insecticides.', 'AG', TRUE),
  (72130, 'Livestock Purchases — Trading', 7, 72, 'Dr', 'Posting', 'PL', 'Z', 'Operating', 'Cost of Sales', 'Store cattle, sheep, weaners purchased for finishing.', 'AG', TRUE),
  (72140, 'Feed & Forage Purchases', 7, 72, 'Dr', 'Posting', 'PL', 'Z', 'Operating', 'Cost of Sales', 'Compound feed, straights, hay, silage.', 'AG', TRUE),
  (73075, 'Subcontract Labour — CIS Net Status', 7, 73, 'Dr', 'Posting', 'PL', 'OS', 'Operating', 'Cost of Sales', 'Payments to subcontractors taxed at 20% under CIS.', 'CN', TRUE),
  (73080, 'Subcontract Labour — CIS Gross Status', 7, 73, 'Dr', 'Posting', 'PL', 'OS', 'Operating', 'Cost of Sales', 'Payments to subcontractors with gross payment status.', 'CN', TRUE),
  (73090, 'Subcontract Labour — Unregistered (CIS 30%)', 7, 73, 'Dr', 'Posting', 'PL', 'OS', 'Operating', 'Cost of Sales', 'Payments to unverified subcontractors taxed at 30%.', 'CN', TRUE),
  (73091, 'Kitchen Brigade Wages — Direct', 7, 73, 'Dr', 'Posting', 'PL', 'OS', 'Operating', 'Cost of Sales', 'Wages of chefs and kitchen staff.', 'HP', TRUE),
  (73092, 'Front-of-House Wages — Direct', 7, 73, 'Dr', 'Posting', 'PL', 'OS', 'Operating', 'Cost of Sales', 'Wages of waiters and bar staff.', 'HP', TRUE),
  (73093, 'Tronc Distribution to Staff', 7, 73, 'Dr', 'Posting', 'PL', 'OS', 'Operating', 'Cost of Sales', 'Tronc payments distributed (does not attract employer NI under approved tronc).', 'HP', TRUE),
  (73100, 'Care Worker Wages — Day', 7, 73, 'Dr', 'Posting', 'PL', 'OS', 'Operating', 'Cost of Sales', 'Daytime care staff wages.', 'CR', TRUE),
  (73110, 'Care Worker Wages — Night', 7, 73, 'Dr', 'Posting', 'PL', 'OS', 'Operating', 'Cost of Sales', 'Sleep-in / waking night staff wages.', 'CR', TRUE),
  (73120, 'Nursing Staff Wages (RGN / RMN)', 7, 73, 'Dr', 'Posting', 'PL', 'OS', 'Operating', 'Cost of Sales', 'Registered nurses (separate from care workers for FNC reporting).', 'CR', TRUE),
  (73130, 'Agency Care & Nursing Staff', 7, 73, 'Dr', 'Posting', 'PL', 'S20', 'Operating', 'Cost of Sales', 'Cost of agency staff cover.', 'CR', TRUE),
  (74070, 'Site Establishment & Welfare', 7, 74, 'Dr', 'Posting', 'PL', 'S20', 'Operating', 'Cost of Sales', 'Site offices, welfare facilities, security.', 'CN', TRUE),
  (74080, 'Plant Hire & Equipment Rental', 7, 74, 'Dr', 'Posting', 'PL', 'S20', 'Operating', 'Cost of Sales', 'External plant and equipment hire on contracts.', 'CN', TRUE),
  (74090, 'Site PPE, H&S and Site Consumables', 7, 74, 'Dr', 'Posting', 'PL', 'S20', 'Operating', 'Cost of Sales', 'PPE, signage, fencing, consumables.', 'CN', TRUE),
  (74100, 'Veterinary, Medicines & AI', 7, 74, 'Dr', 'Posting', 'PL', 'S20', 'Operating', 'Cost of Sales', 'Vet fees, medicines, semen, embryo transfer.', 'AG', TRUE),
  (74110, 'Contract Operations — Inwards', 7, 74, 'Dr', 'Posting', 'PL', 'S20', 'Operating', 'Cost of Sales', 'Contract harvesting, spraying, hedge-cutting.', 'AG', TRUE),
  (74120, 'Fuel — Red Diesel & Farm Vehicles', 7, 74, 'Dr', 'Posting', 'PL', 'S20', 'Operating', 'Cost of Sales', 'Red diesel for agricultural use.', 'AG', TRUE),
  (74130, 'Crop Storage, Drying & Haulage', 7, 74, 'Dr', 'Posting', 'PL', 'S20', 'Operating', 'Cost of Sales', 'Off-farm storage, drying, post-harvest haulage.', 'AG', TRUE),
  (74140, 'Personal Care Supplies & Continence Aids', 7, 74, 'Dr', 'Posting', 'PL', 'S20', 'Operating', 'Cost of Sales', 'Pads, gloves, wipes, dressings.', 'CR', TRUE),
  (74150, 'Medication Costs (Resident-Specific)', 7, 74, 'Dr', 'Posting', 'PL', 'EX', 'Operating', 'Cost of Sales', 'Resident-specific medications not recharged.', 'CR', TRUE),
  (74160, 'Food & Catering for Residents', 7, 74, 'Dr', 'Posting', 'PL', 'Z', 'Operating', 'Cost of Sales', 'Food and catering supplies for residents.', 'CR', TRUE),
  (77000, 'CHARITABLE ACTIVITIES — DIRECT COSTS', 7, 77, 'Dr', 'Header', 'PL', NULL, 'Operating', 'Charitable Activities', 'Heading only — do not post', 'CH', TRUE),
  (77010, 'Grants Made to Individuals (Beneficiaries)', 7, 77, 'Dr', 'Posting', 'PL', 'OS', 'Operating', 'Charitable Activities', 'Direct grants to individual beneficiaries.', 'CH', TRUE),
  (77020, 'Grants Made to Other Charities / Bodies', 7, 77, 'Dr', 'Posting', 'PL', 'OS', 'Operating', 'Charitable Activities', 'Grants paid onward to other charitable bodies / partners.', 'CH', TRUE),
  (77030, 'Direct Programme Staff Costs', 7, 77, 'Dr', 'Posting', 'PL', 'OS', 'Operating', 'Charitable Activities', 'Salaries of staff working directly on charitable activities.', 'CH', TRUE),
  (77040, 'Programme Materials & Supplies', 7, 77, 'Dr', 'Posting', 'PL', 'S20', 'Operating', 'Charitable Activities', 'Direct materials consumed in programme delivery.', 'CH', TRUE),
  (77050, 'Volunteer Expenses', 7, 77, 'Dr', 'Posting', 'PL', 'OS', 'Operating', 'Charitable Activities', 'Reimbursed travel and out-of-pocket expenses for volunteers.', 'CH', TRUE),
  (77060, 'Beneficiary Travel & Subsistence', 7, 77, 'Dr', 'Posting', 'PL', 'OS', 'Operating', 'Charitable Activities', 'Costs of supporting beneficiaries'' travel.', 'CH', TRUE),
  (77070, 'Direct Premises Costs — Programme Use', 7, 77, 'Dr', 'Posting', 'PL', 'S20', 'Operating', 'Charitable Activities', 'Premises costs directly attributable to charitable activities.', 'CH', TRUE),
  (78000, 'RAISING FUNDS — DIRECT COSTS', 7, 78, 'Dr', 'Header', 'PL', NULL, 'Operating', 'Cost of Raising Funds', 'Heading only — do not post', 'CH', TRUE),
  (78010, 'Fundraising Staff Costs', 7, 78, 'Dr', 'Posting', 'PL', 'OS', 'Operating', 'Cost of Raising Funds', 'Salaries of fundraising team.', 'CH', TRUE),
  (78020, 'Fundraising Events — Direct Costs', 7, 78, 'Dr', 'Posting', 'PL', 'S20', 'Operating', 'Cost of Raising Funds', 'Direct costs of fundraising events.', 'CH', TRUE),
  (78030, 'Direct Marketing & Appeals', 7, 78, 'Dr', 'Posting', 'PL', 'S20', 'Operating', 'Cost of Raising Funds', 'Mailings, digital campaigns, printed appeals.', 'CH', TRUE),
  (78040, 'Professional Fundraisers'' Fees', 7, 78, 'Dr', 'Posting', 'PL', 'S20', 'Operating', 'Cost of Raising Funds', 'Fees to commercial participators and professional fundraisers.', 'CH', TRUE),
  (78050, 'Charity Shop — Cost of Sales', 7, 78, 'Dr', 'Posting', 'PL', 'S20', 'Operating', 'Cost of Raising Funds', 'Bought-in stock, shop running costs.', 'CH', TRUE),
  (78060, 'Investment Management Fees', 7, 78, 'Dr', 'Posting', 'PL', 'EX', 'Operating', 'Cost of Raising Funds', 'Fees of investment managers.', 'CH', TRUE),
  (79000, 'SUPPORT COSTS ALLOCATED TO ACTIVITIES', 7, 79, 'Dr', 'Header', 'PL', NULL, 'Operating', 'Support Costs', 'Heading only — do not post', 'CH', TRUE),
  (79010, 'Support Costs — Allocated to Charitable Activities', 7, 79, 'Dr', 'Posting', 'PL', 'OS', 'Operating', 'Support Costs', 'Apportioned share of central support costs (SORP 8).', 'CH', TRUE),
  (79020, 'Support Costs — Allocated to Raising Funds', 7, 79, 'Dr', 'Posting', 'PL', 'OS', 'Operating', 'Support Costs', 'Apportioned share of support to fundraising activity.', 'CH', TRUE),
  (79030, 'Governance Costs — Trustees & AGM', 7, 79, 'Dr', 'Posting', 'PL', 'OS', 'Operating', 'Governance Costs', 'Trustees'' meetings, AGM, governance review.', 'CH', TRUE),
  (79040, 'Governance Costs — Statutory Audit', 7, 79, 'Dr', 'Posting', 'PL', 'S20', 'Operating', 'Governance Costs', 'External statutory audit / independent examination fees.', 'CH', TRUE),
  (79050, 'Governance Costs — Strategic Planning', 7, 79, 'Dr', 'Posting', 'PL', 'OS', 'Operating', 'Governance Costs', 'Strategic planning, regulatory advice, charity registration.', 'CH', TRUE),
  (80000, 'CHARITY GOVERNANCE & TRUSTEE COSTS', 8, 80, 'Dr', 'Header', 'PL', NULL, 'Operating', 'Governance Costs', 'Heading only — do not post', 'CH', TRUE),
  (80010, 'Trustees'' Expenses (Reimbursed)', 8, 80, 'Dr', 'Posting', 'PL', 'OS', 'Operating', 'Governance Costs', 'Reimbursement of trustees'' out-of-pocket expenses.', 'CH', TRUE),
  (80020, 'Trustees'' Indemnity Insurance', 8, 80, 'Dr', 'Posting', 'PL', 'EX', 'Operating', 'Governance Costs', 'Liability insurance for trustees (CC49).', 'CH', TRUE),
  (80030, 'Charity Commission Filing & Compliance', 8, 80, 'Dr', 'Posting', 'PL', 'OS', 'Operating', 'Governance Costs', 'Annual returns, regulatory compliance.', 'CH', TRUE),
  (80040, 'Safeguarding Policy & DBS Costs', 8, 80, 'Dr', 'Posting', 'PL', 'S20', 'Operating', 'Governance Costs', 'DBS checks, safeguarding training, policy work.', 'CH', TRUE),
  (80050, 'Trustee Recruitment & Induction', 8, 80, 'Dr', 'Posting', 'PL', 'OS', 'Operating', 'Governance Costs', 'Costs of recruiting and inducting trustees.', 'CH', TRUE),
  (83075, 'Kitchen Equipment Repairs & Maintenance', 8, 83, 'Dr', 'Posting', 'PL', 'S20', 'Operating', 'Administrative Expenses', 'Kitchen equipment repair and servicing.', 'HP', TRUE),
  (86075, 'Licensing — Premises, Music, Alcohol', 8, 86, 'Dr', 'Posting', 'PL', 'EX', 'Operating', 'Administrative Expenses', 'Premises licence, PRS/PPL music licences, personal licences.', 'HP', TRUE),
  (86085, 'Food Hygiene & EHO Compliance', 8, 86, 'Dr', 'Posting', 'PL', 'S20', 'Operating', 'Administrative Expenses', 'HACCP, food hygiene certificates, pest control.', 'HP', TRUE),
  (86090, 'Booking Platform & Reservation Fees', 8, 86, 'Dr', 'Posting', 'PL', 'S20', 'Operating', 'Administrative Expenses', 'OpenTable, ResDiary, Deliveroo / UberEats commissions.', 'HP', TRUE),
  (87075, 'Architect & Quantity Surveyor Fees', 8, 87, 'Dr', 'Posting', 'PL', 'S20', 'Operating', 'Administrative Expenses', 'Professional fees for QS, architects, structural engineers.', 'CN', TRUE),
  (87085, 'Contract Insurance — All Risks & PI', 8, 87, 'Dr', 'Posting', 'PL', 'EX', 'Operating', 'Administrative Expenses', 'Contract works, public liability, professional indemnity.', 'CN', TRUE),
  (87090, 'Bonds, Warranties & Performance Guarantees', 8, 87, 'Dr', 'Posting', 'PL', 'EX', 'Operating', 'Administrative Expenses', 'Performance bonds and warranty fees.', 'CN', TRUE),
  (87100, 'CQC Registration & Fees', 8, 87, 'Dr', 'Posting', 'PL', 'EX', 'Operating', 'Administrative Expenses', 'Annual CQC fees and registration costs.', 'CR', TRUE),
  (87110, 'Safeguarding, DBS & Training', 8, 87, 'Dr', 'Posting', 'PL', 'S20', 'Operating', 'Administrative Expenses', 'Mandatory care training, DBS checks, safeguarding compliance.', 'CR', TRUE),
  (87120, 'Clinical Governance & Quality Audit', 8, 87, 'Dr', 'Posting', 'PL', 'S20', 'Operating', 'Administrative Expenses', 'Internal audit, mock CQC inspections, governance consultancy.', 'CR', TRUE),
  (87130, 'Resident Insurance & Public Liability', 8, 87, 'Dr', 'Posting', 'PL', 'EX', 'Operating', 'Administrative Expenses', 'Public liability, medical malpractice cover.', 'CR', TRUE),
  (90000, 'GAINS & LOSSES ON CHARITY INVESTMENTS', 9, 90, 'Dr', 'Header', 'PL', NULL, 'Investing', 'Gains/Losses on Investments', 'Heading only — do not post', 'CH', TRUE),
  (90010, 'Realised Gain / (Loss) on Investment Sales', 9, 90, 'Dr', 'Posting', 'PL', 'OS', 'Investing', 'Gains/Losses on Investments', 'Realised gain or loss on sale of investments.', 'CH', TRUE),
  (90020, 'Unrealised Gain / (Loss) — Investment Revaluation', 9, 90, 'Dr', 'Posting', 'PL', 'OS', 'Investing', 'Gains/Losses on Investments', 'Movement in fair value of investments at year-end.', 'CH', TRUE),
  (90030, 'Gain / (Loss) on Endowment Capital', 9, 90, 'Dr', 'Posting', 'PL', 'OS', 'Investing', 'Gains/Losses on Investments', 'Capital gain or loss attributable to endowment funds.', 'CH', TRUE),
  (90040, 'Actuarial Gain / (Loss) on Defined Benefit Scheme', 9, 90, 'Dr', 'Posting', 'PL', 'OS', 'Operating', 'Other Recognised Gains/Losses', 'Remeasurement of multi-employer defined benefit pension scheme.', 'CH', TRUE),
  (90050, 'Gain / (Loss) on Fair Valuation of Biological Assets', 9, 90, 'Dr', 'Posting', 'PL', 'OS', 'Operating', 'Other Gains/Losses', 'FRS 102 s.34 fair value movement.', 'AG', TRUE),
  (92070, 'Endowment Investment Income — Dividends', 9, 92, 'Cr', 'Posting', 'PL', 'OS', 'Investing', 'Investment Income', 'Dividend income on permanent and expendable endowment investments.', 'CH', TRUE),
  (92080, 'Endowment Investment Income — Interest', 9, 92, 'Cr', 'Posting', 'PL', 'OS', 'Investing', 'Investment Income', 'Interest on investments held within endowment.', 'CH', TRUE),
  (92090, 'CIF / CAIF Distribution Income', 9, 92, 'Cr', 'Posting', 'PL', 'OS', 'Investing', 'Investment Income', 'Distributions from Common Investment Funds.', 'CH', TRUE);

INSERT INTO public.hmrc_categories (id, code, name, applies_to_entity_type, maps_to_account_code) VALUES
  ('925f2f6d-5d23-56b8-ad1e-4c9b0c99345c', 'turnover', 'Revenue / Turnover', 'sole_trader', NULL),
  ('a7d14c38-6e47-5c39-a880-88c82c4aeea7', 'cost_of_goods', 'Cost of goods for resale or materials', 'sole_trader', 71010),
  ('b8576cd5-973a-54d0-8b90-b07e42f6d886', 'car_and_travel', 'Car, van and travel expenses', 'sole_trader', 73030),
  ('c591b50f-8975-5241-b20e-d3b8450cb177', 'staff_costs', 'Wages, salaries and other staff costs', 'sole_trader', 73060),
  ('821ae70f-1b45-5c00-ba4a-f01ed4ec80a0', 'premises_rent', 'Rent, rates, power and insurance costs', 'sole_trader', 73010),
  ('6f96fdac-05c0-5af9-91c6-7c44b5ac8554', 'repairs_maintenance', 'Repairs and maintenance of property and equipment', 'sole_trader', 73020),
  ('3de2d841-4eda-5e4c-a1a1-430a31834667', 'office_admin', 'Phone, fax, stationery and other office costs', 'sole_trader', 73050),
  ('19000c85-aba8-53fd-8d0a-f362c1f65fcd', 'advertising', 'Advertising and business entertaining costs', 'sole_trader', 73040),
  ('685184f9-a8c1-5f38-a59b-7f7122849cc8', 'loan_interest', 'Interest on bank and other loans', 'sole_trader', 81010),
  ('4bfa78b6-ab61-5576-a6b1-99ef8681526b', 'bank_charges', 'Bank, credit card and other financial charges', 'sole_trader', 73080),
  ('af6d6b5b-aa37-5ffd-9a63-8d6bc4068793', 'legal_accounting', 'Accountancy, legal and other professional fees', 'sole_trader', 73070),
  ('49576aba-a5d7-526d-9e96-f45a5aa2f2f8', 'other_expenses', 'Other business expenses', 'sole_trader', 73090),
  ('b1cddabb-8796-5d2d-bca5-88c6a36bb681', 'rent_received', 'Rent and other income from property', 'landlord', NULL),
  ('19deca97-9399-5bc4-be92-7d5d34ef4c0d', 'rates_insurance', 'Rent, rates, insurance, ground rents, etc.', 'landlord', 73010),
  ('4c6e37d0-2529-548e-8074-b7f8d15a9dd0', 'property_repairs', 'Property repairs and maintenance', 'landlord', 73020),
  ('204dbf4f-1f82-55d8-874e-29e6a6b15e9d', 'finance_costs', 'Non-residential property finance costs', 'landlord', 81010),
  ('b478a81b-332a-5d1b-896c-8d88b011aeb1', 'legal_professional', 'Legal, management and other professional fees', 'landlord', 73070),
  ('ac3414aa-f7d1-5bde-932a-55ee3a628e38', 'other_landlord', 'Other landlord expenses', 'landlord', 73090);

COMMIT;